import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import ConsentChecklist from "./ConsentChecklist";

const validSpanishId = (raw:string) => { const value=raw.toUpperCase().replace(/[\s-]/g,""); const normalized=/^[XYZ]/.test(value)?`${({X:"0",Y:"1",Z:"2"} as Record<string,string>)[value[0]]}${value.slice(1)}`:value; return /^\d{8}[A-Z]$/.test(normalized) && "TRWAGMYFPDXBNJZSQVHLCKE"[Number(normalized.slice(0,8))%23]===normalized[8]; };
const validPhone = (raw:string) => /^(?:\+34)?[6789]\d{8}$/.test(raw.replace(/[\s.-]/g,""));
const validBirthDate = (raw:string) => Boolean(raw) && !Number.isNaN(new Date(`${raw}T00:00:00`).getTime()) && new Date(`${raw}T00:00:00`) <= new Date();

export default function AdultRegistration({ email, onBack }: { email: string; onBack: () => void }) {
  const storageKey = `club:adult-registration:${email}`; const stored = (() => { try { return JSON.parse(sessionStorage.getItem(storageKey) || "{}"); } catch { return {}; } })();
  const [step, setStep] = useState(stored.step || 1); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  const [data, setData] = useState(stored.data || { first_name: "", last_name: "", dni_nie: "", phone: "", birth_date: "", federative_sex: "M", training_group_id: "", nationality: "Española", birthplace: "", previous_license: "", previous_club: "", relevant_condition: false, relevant_condition_detail: "", asthma_allergy_medication: "", injury_limitation: "", support_needs: "", health_notes: "" });
  const [groups, setGroups] = useState<{ id: string; name: string; category_label: string; schedule_days: string | null; starts_at: string | null; ends_at: string | null }[]>([]);
  const [plan, setPlan] = useState<"monthly" | "term">("monthly");
  const [consents, setConsents] = useState<Record<string, boolean>>({ privacy: false, health_data: false, image_use: false, fam_data: false, club_rules: false, recurring_payment: false });
  const [cardReady, setCardReady] = useState(() => new URLSearchParams(window.location.search).get("payment_method") === "updated" || Boolean(stored.cardReady));
  const update = (key: keyof typeof data, value: string | boolean) => setData(current => ({ ...current, [key]: value }));
  const seasonYear = new Date().getFullYear() + (new Date().getMonth() >= 6 ? 1 : 0);
  const trainingCategory = !data.birth_date ? "" : (() => { const age = seasonYear - Number(data.birth_date.slice(0, 4)); if (age <= 5) return "Sub 6"; if (age <= 7) return "Sub 8"; if (age <= 9) return "Sub 10"; if (age <= 11) return "Sub 12"; if (age <= 13) return "Sub 14"; if (age <= 15) return "Sub 16"; if (age <= 17) return "Sub 18"; if (age <= 19) return "Sub 20"; if (age <= 22) return "Sub 23"; return "Absoluto / Máster"; })();
  const availableGroups = groups.filter(group => group.category_label.toLowerCase().includes(trainingCategory.toLowerCase()) || (/sub 23|absoluto/.test(trainingCategory.toLowerCase()) && /m[aá]ster|master|running|absoluto/.test(`${group.name} ${group.category_label}`.toLowerCase())));
  const valid = Boolean(data.first_name.trim() && data.last_name.trim() && validSpanishId(data.dni_nie) && validPhone(data.phone) && validBirthDate(data.birth_date) && data.training_group_id && (trainingCategory === "Sub 6" || (data.nationality.trim() && data.birthplace.trim())));
  const acceptAll = Object.values(consents).every(Boolean);
  useEffect(() => { sessionStorage.setItem(storageKey, JSON.stringify({ step, data, plan, consents, cardReady })); }, [storageKey, step, data, plan, consents, cardReady]);
  useEffect(() => { if (!supabase) return; void supabase.from("training_groups").select("id,name,category_label,schedule_days,starts_at,ends_at").eq("active", true).order("name").then(({ data }) => setGroups((data || []) as typeof groups)); }, []);
  const addCard = async () => { if (!supabase) return; setBusy(true); setError(""); const { data: sessionData } = await supabase.auth.getSession(); const response = await fetch("/api/create-payment-method-setup", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${sessionData.session?.access_token || ""}` }, body: JSON.stringify({ returnTo: "adult" }) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok || !body.url) return setError(body.error || "No se pudo abrir Stripe."); window.location.assign(body.url); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; if (!cardReady) return setError("Añade la tarjeta segura antes de enviar la solicitud."); setBusy(true); setError(""); const { error: rpcError } = await supabase.rpc("submit_adult_registration", { payload: { ...data, plan, consents: Object.keys(consents).filter(key => consents[key]) } }); setBusy(false); if (rpcError) return setError(rpcError.message); sessionStorage.removeItem(storageKey); setSent(true); };
  if (sent) return <main className="register-page"><section className="register-brand"><div className="brand"><i>AF</i><div><b>CLUB ATLETAS</b><small>DE FUENLABRADA</small></div></div><div><span>SOLICITUD RECIBIDA</span><h1>Ya está<br />en revisión.</h1><p>La licencia se mantiene pendiente hasta que el club la tramite. No se ha realizado ningún cargo.</p></div></section><section className="register-form"><div className="form-wrap"><h2>Tu perfil se ha enviado</h2><p>Recibirás la solicitud segura de tarjeta cuando el administrador apruebe el alta y active el proveedor de cobro.</p><button className="primary-wide" onClick={onBack}>Salir de la cuenta</button></div></section></main>;
  return <main className="register-page"><section className="register-brand"><div className="brand"><i>AF</i><div><b>CLUB ATLETAS</b><small>DE FUENLABRADA</small></div></div><div><span>ALTA DIGITAL · PASO {step} DE 3</span><h1>Tu perfil,<br />en un solo lugar.</h1><p>Cuenta: {email}. Los atletas mayores de 18 años gestionan su propia ficha.</p></div></section><section className="register-form"><button className="back" onClick={onBack}>← Cerrar sesión</button><form className="form-wrap full-registration" onSubmit={submit}>
    {step === 1 && <><small className="step">1 · DATOS DEL ATLETA</small><h2>Tu información personal</h2><div className="field-grid"><label>Nombre<input required value={data.first_name} onChange={e => update("first_name", e.target.value)} /></label><label>Apellidos<input required value={data.last_name} onChange={e => update("last_name", e.target.value)} /></label><label>Fecha de nacimiento<input required type="date" max={new Date().toISOString().slice(0,10)} value={data.birth_date} onChange={e => { update("birth_date", e.target.value); update("training_group_id", ""); }} /></label><label>Sexo federativo<select value={data.federative_sex} onChange={e => update("federative_sex", e.target.value)}><option value="M">Masculino</option><option value="F">Femenino</option></select></label><label>Teléfono móvil<input required type="tel" inputMode="tel" placeholder="600123123" value={data.phone} onChange={e => update("phone", e.target.value)} /></label><label>DNI / NIE<input required placeholder="12345678Z o X1234567L" value={data.dni_nie} onChange={e => update("dni_nie", e.target.value)} /></label><label className="wide">Correo de la cuenta<input disabled value={email} /></label>{trainingCategory && <label className="wide">Grupo de entrenamiento recomendado · {trainingCategory}<select required value={data.training_group_id} onChange={e => update("training_group_id", e.target.value)}><option value="">Selecciona grupo u horario</option>{availableGroups.map(group => <option key={group.id} value={group.id}>{group.name} · {group.schedule_days}{group.starts_at ? ` · ${group.starts_at.slice(0, 5)}–${group.ends_at?.slice(0, 5)}` : ""}</option>)}</select></label>}</div>{trainingCategory && trainingCategory !== "Sub 6" && <fieldset className="federation-form"><legend>Ficha federativa FAM</legend><p>Se guardará con tu solicitud para tramitar la licencia.</p><div className="field-grid"><label>Nacionalidad<input required value={data.nationality} onChange={e => update("nationality", e.target.value)} /></label><label>Localidad de nacimiento<input required value={data.birthplace} onChange={e => update("birthplace", e.target.value)} /></label><label>Licencia anterior<input value={data.previous_license} onChange={e => update("previous_license", e.target.value)} /></label><label>Club anterior<input value={data.previous_club} onChange={e => update("previous_club", e.target.value)} /></label></div></fieldset>}<button type="button" disabled={!valid} className="primary-wide" onClick={() => setStep(2)}>Información de salud →</button></>}
    {step === 2 && <><small className="step">2 · INFORMACIÓN DE SALUD</small><h2>Entrenar con seguridad</h2><p>Esta información estará visible únicamente para administración y tu entrenador asignado.</p><label className="check-line"><input type="checkbox" checked={data.relevant_condition} onChange={e => update("relevant_condition", e.target.checked)} />Tengo alguna patología o información sanitaria relevante</label><label>Detalle<textarea value={data.relevant_condition_detail} onChange={e => update("relevant_condition_detail", e.target.value)} /></label><label>Asma, alergias o medicación<textarea value={data.asthma_allergy_medication} onChange={e => update("asthma_allergy_medication", e.target.value)} /></label><label>Lesiones o limitaciones<textarea value={data.injury_limitation} onChange={e => update("injury_limitation", e.target.value)} /></label><label>Necesidades de apoyo<textarea value={data.support_needs} onChange={e => update("support_needs", e.target.value)} /></label><label>Otra información<textarea value={data.health_notes} onChange={e => update("health_notes", e.target.value)} /></label><div className="form-actions"><button type="button" className="secondary" onClick={() => setStep(1)}>Atrás</button><button type="button" onClick={() => setStep(3)}>Consentimientos y cuota →</button></div></>}
    {step === 3 && <><small className="step">3 · CONSENTIMIENTOS Y CUOTA</small><h2>Enviar para revisión</h2><p>Abre cada documento con el símbolo ＋ para leer lo que aceptas.</p><ConsentChecklist values={consents} onChange={(key, checked) => setConsents(current => ({ ...current, [key]: checked }))} /><div className="plan-select"><b>Tipo de cuota</b><button type="button" aria-pressed={plan === "monthly"} className={plan === "monthly" ? "chosen" : ""} onClick={() => setPlan("monthly")}>Mensual · 35 €</button><button type="button" aria-pressed={plan === "term"} className={plan === "term" ? "chosen" : ""} onClick={() => setPlan("term")}>Trimestral · 70 €</button></div><div className="plan-select"><b>Tarjeta obligatoria</b><p>{cardReady ? "Tarjeta añadida de forma segura en Stripe." : "El club no recibe ni guarda el número de tarjeta ni el CVV."}</p>{!cardReady && <button type="button" disabled={busy} onClick={() => void addCard()}>Añadir tarjeta segura en Stripe</button>}</div>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={() => setStep(2)}>Atrás</button><button disabled={!acceptAll || !cardReady || busy}>{busy ? "Enviando…" : "Enviar solicitud para revisión"}</button></div></>}
  </form></section></main>;
}
