import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import "./club-admin-family.css";

type Role = "owner" | "admin" | "coach" | "parent" | "adult_athlete" | "minor_athlete";
type Profile = { id: string; email: string; full_name: string | null; role: Role };
type Group = { id: string; name: string; category_label: string; colour: string; active: boolean; schedule_days?: string | null; starts_at?: string | null; ends_at?: string | null; season?: string | null };
type Athlete = { id: string; first_name: string; last_name: string; club_status: string; license_status: string; license_number: string | null; training_group_id: string | null; family_id: string | null; training_groups?: Group | null };
type Attendance = { athlete_id: string; attended: boolean | null; marked_at: string | null; attendance_sessions?: { starts_at: string }[] | null };
type Product = { id: string; name: string; description: string | null; price_cents: number; sizes: string[]; active: boolean };

const euro = (cents: number) => new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100);
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString("es-ES", { day: "2-digit", month: "short", year: "numeric" }) : "Pendiente";

export function GroupManager() {
  const [groups, setGroups] = useState<Group[]>([]); const [coaches, setCoaches] = useState<Profile[]>([]); const [links, setLinks] = useState<{ training_group_id: string; coach_profile_id: string }[]>([]);
  const [selectedId, setSelectedId] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const blank = { name: "", category_label: "", colour: "#2563eb", schedule_days: "", starts_at: "", ends_at: "", season: "2026", active: true };
  const [form, setForm] = useState(blank); const [coachIds, setCoachIds] = useState<string[]>([]);
  const selected = groups.find(item => item.id === selectedId);
  const load = async () => { if (!supabase) return; const [{ data: groupData }, { data: coachData }, { data: linkData }] = await Promise.all([supabase.from("training_groups").select("*").order("name"), supabase.from("profiles").select("id,email,full_name,role").eq("role", "coach").order("full_name"), supabase.from("training_group_coaches").select("training_group_id,coach_profile_id")]); setGroups((groupData ?? []) as Group[]); setCoaches((coachData ?? []) as Profile[]); setLinks((linkData ?? []) as typeof links); };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!selected) return; setForm({ name: selected.name, category_label: selected.category_label, colour: selected.colour, schedule_days: selected.schedule_days || "", starts_at: selected.starts_at?.slice(0, 5) || "", ends_at: selected.ends_at?.slice(0, 5) || "", season: selected.season || "2026", active: selected.active }); setCoachIds(links.filter(link => link.training_group_id === selected.id).map(link => link.coach_profile_id)); setNotice(""); }, [selectedId, groups.length, links.length]);
  const newGroup = () => { setSelectedId(""); setForm(blank); setCoachIds([]); setNotice(""); };
  const save = async (e: FormEvent) => { e.preventDefault(); if (!supabase) return; setSaving(true); setNotice(""); const payload = { ...form, schedule_days: form.schedule_days || null, starts_at: form.starts_at || null, ends_at: form.ends_at || null }; const result = selectedId ? await supabase.from("training_groups").update(payload).eq("id", selectedId).select("id").single() : await supabase.from("training_groups").insert(payload).select("id").single(); if (result.error || !result.data) { setSaving(false); return setNotice(result.error?.message || "No se pudo guardar el grupo."); } const groupId = result.data.id; const { error: clearError } = await supabase.from("training_group_coaches").delete().eq("training_group_id", groupId); if (clearError) { setSaving(false); return setNotice(clearError.message); } if (coachIds.length) { const { error } = await supabase.from("training_group_coaches").insert(coachIds.map(coach_profile_id => ({ training_group_id: groupId, coach_profile_id }))); if (error) { setSaving(false); return setNotice(error.message); } } setSelectedId(groupId); setSaving(false); setNotice("Grupo y entrenadores guardados."); void load(); };
  return <><div className="page-head"><div><h1>Grupos</h1><p>Abre un grupo para cambiar horario, temporada y entrenadores.</p></div><button onClick={newGroup}>Nuevo grupo</button></div><section className="cards">{groups.map(group => <button key={group.id} className={`panel group-card group-button ${selectedId === group.id ? "selected-row" : ""}`} onClick={() => setSelectedId(group.id)}><i style={{ background: group.colour }} /><h2>{group.name}</h2><p>{group.category_label}</p><small>{group.schedule_days ? `${group.schedule_days} · ${group.starts_at?.slice(0, 5)}–${group.ends_at?.slice(0, 5)}` : "Horario pendiente"}</small><small>{links.filter(link => link.training_group_id === group.id).length} entrenador(es)</small></button>)}</section><form className="panel group-editor" onSubmit={save}><h2>{selected ? `Ficha: ${selected.name}` : "Nuevo grupo"}</h2><div className="ops-grid"><label>Nombre<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Categoría<input required value={form.category_label} onChange={e => setForm({ ...form, category_label: e.target.value })} /></label><label>Días de entrenamiento<input value={form.schedule_days} onChange={e => setForm({ ...form, schedule_days: e.target.value })} placeholder="Lunes y miércoles" /></label><label>Inicio<input type="time" value={form.starts_at} onChange={e => setForm({ ...form, starts_at: e.target.value })} /></label><label>Fin<input type="time" value={form.ends_at} onChange={e => setForm({ ...form, ends_at: e.target.value })} /></label><label>Temporada<input value={form.season} onChange={e => setForm({ ...form, season: e.target.value })} /></label><label>Color<input type="color" value={form.colour} onChange={e => setForm({ ...form, colour: e.target.value })} /></label><label className="check-line"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} />Activo</label></div><fieldset className="coach-picker"><legend>Entrenadores asignados</legend>{coaches.length ? coaches.map(coach => <label key={coach.id}><input type="checkbox" checked={coachIds.includes(coach.id)} onChange={e => setCoachIds(e.target.checked ? [...coachIds, coach.id] : coachIds.filter(id => id !== coach.id))} />{coach.full_name || coach.email}<small>{coach.email}</small></label>) : <p>No hay entrenadores con cuenta todavía. Crea la invitación desde «Invitaciones».</p>}</fieldset><button disabled={saving}>{saving ? "Guardando…" : "Guardar grupo y entrenadores"}</button>{notice && <p className={notice.startsWith("Grupo") ? "success-note" : "error-note"}>{notice}</p>}</form></>;
}

export function FamilyHome({ profile }: { profile: Profile }) {
  const [athletes, setAthletes] = useState<Athlete[]>([]); const [records, setRecords] = useState<Attendance[]>([]); const [payments, setPayments] = useState<{ id: string; description: string; amount_cents: number; scheduled_for: string | null; status: string }[]>([]); const [pref, setPref] = useState({ enabled: false, app: true, email: false }); const [familyId, setFamilyId] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { if (!supabase) return; const [{ data: athleteData }, { data: recordData }, { data: paymentData }] = await Promise.all([supabase.from("athletes").select("*,training_groups(*)"), supabase.from("attendance_records").select("athlete_id,attended,marked_at,attendance_sessions(starts_at)").order("marked_at", { ascending: false }).limit(30), supabase.from("payment_ledger").select("id,description,amount_cents,scheduled_for,status").order("scheduled_for", { ascending: true })]); const own = (athleteData ?? []) as Athlete[]; setAthletes(own); setRecords((recordData ?? []) as Attendance[]); setPayments((paymentData ?? []) as typeof payments); const family = own.find(item => item.family_id)?.family_id; if (family) { setFamilyId(family); const { data } = await supabase.from("family_notification_preferences").select("enabled,channels").eq("family_id", family).maybeSingle(); if (data) setPref({ enabled: data.enabled, app: data.channels.includes("app"), email: data.channels.includes("email") }); } };
  useEffect(() => { void load(); }, []);
  const savePreference = async () => { if (!supabase || !familyId) return; const channels = [pref.app ? "app" : null, pref.email ? "email" : null].filter(Boolean); const { error } = await supabase.from("family_notification_preferences").upsert({ family_id: familyId, enabled: pref.enabled, channels, updated_at: new Date().toISOString() }); setNotice(error ? error.message : "Preferencias de asistencia guardadas."); };
  const nextPayment = payments.find(item => ["draft", "pending", "due"].includes(item.status)); const upcoming = records.filter(record => record.attendance_sessions?.[0]?.starts_at && new Date(record.attendance_sessions[0].starts_at) > new Date()).slice(0, 3);
  return <><div className="page-head"><div><h1>Hola, {profile.full_name?.split(" ")[0] || "familia"}</h1><p>Resumen de tus atletas, asistencias y próximos pagos.</p></div></div><section className="metric-grid family-metrics"><article className="metric"><small>Atletas inscritos</small><b>{athletes.length}</b></article><article className="metric"><small>Asistencias recientes</small><b>{records.filter(record => record.attended).length}</b></article><article className="metric"><small>Próximo pago</small><b>{nextPayment ? euro(nextPayment.amount_cents) : "—"}</b><small>{nextPayment ? date(nextPayment.scheduled_for) : "No hay pagos pendientes"}</small></article></section><section className="two-columns"><article className="panel"><h2>Mis atletas</h2>{athletes.map(athlete => <div className="summary-line" key={athlete.id}><span><b>{athlete.first_name} {athlete.last_name}</b><small>{athlete.training_groups?.name || "Grupo pendiente"}</small></span><span>{athlete.club_status === "active" ? "Activo" : "En revisión"}</span></div>)}{!athletes.length && <p>No hay atletas asociados a esta cuenta.</p>}</article><article className="panel"><h2>Próximos entrenamientos</h2>{upcoming.length ? upcoming.map(record => <p key={`${record.athlete_id}-${record.marked_at}`}>{date(record.attendance_sessions?.[0]?.starts_at)} · {record.attended ? "Confirmado" : "Pendiente"}</p>) : <p>Las próximas listas de asistencia aparecerán aquí.</p>}</article></section>{familyId && <article className="panel family-preferences"><h2>Avisos de asistencia</h2><p>Elige si quieres que el club te avise cuando el entrenador pase lista de tu hijo/a.</p><label className="check-line"><input type="checkbox" checked={pref.enabled} onChange={e => setPref({ ...pref, enabled: e.target.checked })} />Quiero recibir avisos de asistencia</label><fieldset disabled={!pref.enabled}><legend>Canal preferido</legend><label><input type="checkbox" checked={pref.app} onChange={e => setPref({ ...pref, app: e.target.checked })} />En la aplicación</label><label><input type="checkbox" checked={pref.email} onChange={e => setPref({ ...pref, email: e.target.checked })} />Preparar por email</label></fieldset><small>Los emails quedarán preparados hasta conectar el proveedor de correo del club.</small><button onClick={() => void savePreference()}>Guardar preferencias</button>{notice && <p className={notice.includes("guardadas") ? "success-note" : "error-note"}>{notice}</p>}</article>}</>;
}

export function FamilyAthletes() {
  const [athletes, setAthletes] = useState<Athlete[]>([]); const [records, setRecords] = useState<Attendance[]>([]); const [entries, setEntries] = useState<{ athlete_id: string; status: string; competition_events?: { title: string; starts_at: string }[] | null }[]>([]); const [selectedId, setSelectedId] = useState("");
  const load = async () => { if (!supabase) return; const [{ data: athleteData }, { data: recordData }, { data: entryData }] = await Promise.all([supabase.from("athletes").select("*,training_groups(*)"), supabase.from("attendance_records").select("athlete_id,attended,marked_at,attendance_sessions(starts_at)").order("marked_at", { ascending: false }), supabase.from("competition_entries").select("athlete_id,status,competition_events(title,starts_at)").order("created_at", { ascending: false })]); setAthletes((athleteData ?? []) as Athlete[]); setRecords((recordData ?? []) as Attendance[]); setEntries((entryData ?? []) as typeof entries); };
  useEffect(() => { void load(); }, []); const selected = athletes.find(item => item.id === selectedId);
  return <><div className="page-head"><div><h1>Mis atletas</h1><p>Abre la ficha de cada atleta para consultar grupo, asistencia y carreras.</p></div></div><section className="cards">{athletes.map(athlete => <button key={athlete.id} className={`panel athlete-summary ${selectedId === athlete.id ? "selected-row" : ""}`} onClick={() => setSelectedId(athlete.id)}><h2>{athlete.first_name} {athlete.last_name}</h2><p>{athlete.training_groups?.name || "Grupo pendiente de asignación"}</p><small>Licencia: {athlete.license_status === "active" ? athlete.license_number || "activa" : "pendiente"} · Ver ficha →</small></button>)}</section>{selected && <section className="athlete-detail"><div className="page-head"><div><h1>{selected.first_name} {selected.last_name}</h1><p>Información deportiva y seguimiento de la temporada.</p></div><button className="outline" onClick={() => setSelectedId("")}>Cerrar ficha</button></div><div className="detail-grid"><article className="panel"><h2>Grupo y licencia</h2><p><b>{selected.training_groups?.name || "Sin grupo"}</b></p><p>{selected.training_groups?.schedule_days || "Horario pendiente"} {selected.training_groups?.starts_at ? `· ${selected.training_groups.starts_at.slice(0, 5)}–${selected.training_groups.ends_at?.slice(0, 5)}` : ""}</p><p>Licencia: {selected.license_status === "active" ? selected.license_number || "Activa" : "Pendiente"}</p></article><article className="panel"><h2>Últimas asistencias</h2>{records.filter(record => record.athlete_id === selected.id).slice(0, 6).map(record => <p key={`${record.athlete_id}-${record.marked_at}`}>{date(record.attendance_sessions?.[0]?.starts_at)} · {record.attended ? "Ha asistido" : "No ha asistido"}</p>)}{!records.some(record => record.athlete_id === selected.id) && <p>Aún no hay asistencias registradas.</p>}</article><article className="panel"><h2>Carreras y pruebas</h2>{entries.filter(entry => entry.athlete_id === selected.id).map((entry, index) => <p key={index}><b>{entry.competition_events?.[0]?.title || "Prueba"}</b><br />{date(entry.competition_events?.[0]?.starts_at)} · {entry.status}</p>)}{!entries.some(entry => entry.athlete_id === selected.id) && <p>Aún no hay solicitudes de competición.</p>}</article></div></section>}</>;
}

export function Shop({ profile }: { profile: Profile }) {
  const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<{ id: string; status: string; total_cents: number; created_at: string }[]>([]); const [size, setSize] = useState<Record<string, string>>({}); const [notice, setNotice] = useState(""); const [newProduct, setNewProduct] = useState({ name: "", description: "", price: "", sizes: "XS,S,M,L,XL" });
  const isManager = profile.role === "owner" || profile.role === "admin";
  const load = async () => { if (!supabase) return; const [{ data: productData }, { data: orderData }] = await Promise.all([supabase.from("club_products").select("*").eq("active", true).order("name"), supabase.from("club_orders").select("id,status,total_cents,created_at").order("created_at", { ascending: false })]); setProducts((productData ?? []) as Product[]); setOrders((orderData ?? []) as typeof orders); };
  useEffect(() => { void load(); }, []);
  const order = async (product: Product) => { if (!supabase) return; const productSize = size[product.id] || product.sizes?.[0] || "Única"; const { data, error } = await supabase.from("club_orders").insert({ status: "requested", total_cents: product.price_cents, created_by: profile.id }).select("id").single(); if (error || !data) return setNotice(error?.message || "No se pudo crear el pedido."); const { error: lineError } = await supabase.from("club_order_items").insert({ order_id: data.id, product_id: product.id, product_name: product.name, size: productSize, quantity: 1, unit_price_cents: product.price_cents }); setNotice(lineError ? lineError.message : "Pedido enviado al club. El pago queda pendiente de confirmación."); void load(); };
  const addProduct = async (e: FormEvent) => { e.preventDefault(); if (!supabase) return; const price = Math.round(Number(newProduct.price.replace(",", ".")) * 100); if (!newProduct.name || !Number.isFinite(price)) return setNotice("Indica un nombre y un precio válidos."); const { error } = await supabase.from("club_products").insert({ name: newProduct.name, description: newProduct.description || null, price_cents: price, sizes: newProduct.sizes.split(",").map(item => item.trim()).filter(Boolean), active: true, created_by: profile.id }); setNotice(error ? error.message : "Producto añadido a la tienda."); if (!error) setNewProduct({ name: "", description: "", price: "", sizes: "XS,S,M,L,XL" }); void load(); };
  return <><div className="page-head"><div><h1>Tienda del club</h1><p>Material y equipación. Los pedidos se revisan antes de cobrar.</p></div></div>{isManager && <form className="panel inline-form" onSubmit={addProduct}><label>Producto<input value={newProduct.name} onChange={e => setNewProduct({ ...newProduct, name: e.target.value })} placeholder="Camiseta técnica" /></label><label>Precio (€)<input value={newProduct.price} onChange={e => setNewProduct({ ...newProduct, price: e.target.value })} placeholder="18" /></label><label>Tallas<input value={newProduct.sizes} onChange={e => setNewProduct({ ...newProduct, sizes: e.target.value })} /></label><label>Descripción<input value={newProduct.description} onChange={e => setNewProduct({ ...newProduct, description: e.target.value })} /></label><button>Añadir producto</button></form>}<section className="cards">{products.map(product => <article className="panel product-card" key={product.id}><div className="product-icon">AF</div><h2>{product.name}</h2><p>{product.description || "Equipación oficial del Club Atletas de Fuenlabrada."}</p><b>{euro(product.price_cents)}</b>{product.sizes?.length > 0 && <select value={size[product.id] || product.sizes[0]} onChange={e => setSize({ ...size, [product.id]: e.target.value })}>{product.sizes.map(item => <option key={item}>{item}</option>)}</select>}<button onClick={() => void order(product)}>Solicitar pedido</button></article>)}{!products.length && <article className="panel empty">La tienda aún no tiene productos. El administrador puede añadir el primero aquí arriba.</article>}</section>{notice && <p className={notice.includes("enviado") || notice.includes("añadido") ? "success-note panel" : "error-note panel"}>{notice}</p>}<article className="panel table"><h2>Mis pedidos</h2>{orders.map(order => <div className="row" key={order.id}><span><b>Pedido del club</b><small>{date(order.created_at)}</small></span><span>{euro(order.total_cents)}</span><span>{order.status === "requested" ? "Pendiente de revisión" : order.status}</span></div>)}{!orders.length && <p className="empty">Aún no tienes pedidos.</p>}</article></>;
}
