import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { apiFetch } from "../lib/clubApi";
import "./challenge-icons.css";

type Role="owner"|"admin"|"coach"|"parent"|"adult_athlete"|"minor_athlete";
type Metric="distance"|"activities"|"active_days"|"elevation"|"duration"|"relative_effort";
type Row={athlete_id:string;first_name:string;last_name:string;group_name:string|null;avatar_url?:string|null;activities:number;distance_m:number;moving_time_s:number;elevation_gain_m:number;relative_effort?:number;active_days?:number;longest_streak_days?:number};
type Progress={challenge_id:string;title:string;description:string;metric:Metric;scope:"club"|"group"|"duel";target_value:number;ends_on:string;athlete_id:string;participant_status:"pending"|"accepted"|"declined";first_name:string;last_name:string;group_name:string|null;avatar_url:string|null;progress_value:number};
type Feed={athlete_id:string;first_name:string;last_name:string;avatar_url:string|null;achievement_key:string;title:string;earned_at:string};
const meta:Record<Metric,{label:string;unit:string;target:number}>={distance:{label:"Kilómetros",unit:"km",target:20},activities:{label:"Sesiones",unit:"sesiones",target:4},active_days:{label:"Constancia",unit:"días",target:4},elevation:{label:"Desnivel",unit:"m+",target:500},duration:{label:"Tiempo activo",unit:"min",target:180},relative_effort:{label:"Carga registrada",unit:"puntos",target:250}};
const km=(r?:Row)=>Number(r?.distance_m||0)/1000;
const score=(r:Row|undefined,m:Metric)=>!r?0:m==="distance"?km(r):m==="activities"?Number(r.activities||0):m==="active_days"?Number(r.active_days||0):m==="elevation"?Number(r.elevation_gain_m||0):m==="duration"?Number(r.moving_time_s||0)/60:Number(r.relative_effort||0);
const value=(n:number,m:Metric)=>`${m==="distance"?n.toFixed(1):Math.round(n)} ${meta[m].unit}`;
const initials=(r:{first_name:string;last_name:string})=>`${r.first_name[0]||""}${r.last_name[0]||""}`.toUpperCase();
const weekEnd=()=>{const d=new Date();d.setDate(d.getDate()+7);return d.toISOString().slice(0,10)};
function Avatar({r}:{r:{first_name:string;last_name:string;avatar_url?:string|null}}){return <span className="challenge-person">{r.avatar_url?<img src={r.avatar_url} alt=""/>:<i>{initials(r)}</i>}</span>}
type ProIconName="flame"|"duel"|"flag"|"medal";
function ProIcon({name}:{name:ProIconName}){const paths={flame:<><path d="M13 2c1 4-2 5-2 8-2-2-4-1-5 1-2 4 1 9 6 9s8-4 6-9c-.8-2-2-3-4-5 0 2-.4 3-1 4"/><path d="M12 13c-2 2-2 5 0 5s3-2 2-4c-.4-.8-1.2-1.5-2-2.5"/></>,duel:<><path d="m4 4 7 7m-5-5-2 2m5 5-5 5m0-4 4 4m12-14-7 7m5-5 2 2m-5 5 5 5m0-4-4 4"/><circle cx="12" cy="12" r="2"/></>,flag:<><path d="M5 21V4m0 1c5-3 8 3 14 0v9c-6 3-9-3-14 0"/></>,medal:<><circle cx="12" cy="14" r="5"/><path d="m9 9-3-6h4l2 4 2-4h4l-3 6m-5 5 1.3 1.1L14 12.5"/></>};return <svg className="challenge-pro-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}

export default function ClubChallenge({athleteId,profileId,role}:{athleteId?:string;profileId?:string;role?:Role}){
 const[weekly,setWeekly]=useState<Row[]>([]),[season,setSeason]=useState<Row[]>([]),[progress,setProgress]=useState<Progress[]>([]),[feed,setFeed]=useState<Feed[]>([]);
 const[view,setView]=useState<"home"|"challenges"|"duels"|"ranking"|"achievements">("home"),[period,setPeriod]=useState<"week"|"season">("week"),[metric,setMetric]=useState<Metric>("distance"),[create,setCreate]=useState(false),[notice,setNotice]=useState("");
 const[title,setTitle]=useState(""),[description,setDescription]=useState(""),[createMetric,setCreateMetric]=useState<Metric>("distance"),[scope,setScope]=useState<"club"|"group"|"duel">("club"),[target,setTarget]=useState(20),[ends,setEnds]=useState(weekEnd()),[opponent,setOpponent]=useState("");
 const load=async()=>{const c=supabase;if(!c)return;const[w,s,p,f]=await Promise.all([c.from("club_challenge_weekly").select("*"),c.from("club_challenge_season").select("*"),c.from("club_challenge_progress").select("*").gte("ends_on",new Date().toISOString().slice(0,10)),c.from("club_challenge_recent_achievements").select("*").order("earned_at",{ascending:false}).limit(12)]);setWeekly((w.data||[]) as Row[]);setSeason((s.data||w.data||[]) as Row[]);setProgress((p.data||[]) as Progress[]);setFeed((f.data||[]) as Feed[])};
 useEffect(()=>{void load()},[athleteId]);
 const source=period==="week"?weekly:season,ranked=useMemo(()=>[...source].sort((a,b)=>score(b,metric)-score(a,metric)),[source,metric]);
 const own=season.find(r=>r.athlete_id===athleteId),ownGroup=weekly.find(r=>r.athlete_id===athleteId)?.group_name,streak=Number(own?.longest_streak_days||0);
 const grouped=useMemo(()=>{const m=new Map<string,Progress[]>();progress.forEach(r=>m.set(r.challenge_id,[...(m.get(r.challenge_id)||[]),r]));return[...m.values()]},[progress]);
 const opponents=weekly.filter(r=>r.athlete_id!==athleteId&&(!ownGroup||r.group_name===ownGroup)),canCreate=Boolean(profileId||athleteId||role&&["owner","admin","coach"].includes(role));
 const submit=async(e:FormEvent)=>{e.preventDefault();const c=supabase;if(!c)return;setNotice("Creando reto…");const{data:challengeId,error}=await c.rpc("create_club_challenge",{challenge_title:title,challenge_description:description,challenge_metric:createMetric,challenge_scope:scope,challenge_target:target,challenge_starts:new Date().toISOString().slice(0,10),challenge_ends:ends,acting_athlete_id:athleteId||null,target_group_id:null,invited_athlete_id:scope==="duel"?opponent:null});if(error)return setNotice(error.message);const{data:sessionData}=await c.auth.getSession();let mailOk=true;if(challengeId&&sessionData.session?.access_token){const response=await apiFetch("/api/send-event-notification",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${sessionData.session.access_token}`},body:JSON.stringify({announcementId:challengeId})}).catch(()=>null);mailOk=Boolean(response?.ok)}setNotice(mailOk?"Reto creado y participantes avisados.":"Reto creado; el correo queda pendiente de reintento.");setCreate(false);setTitle("");await load();setView(scope==="duel"?"duels":"challenges")};
 const act=async(id:string,kind:"join"|"accept"|"decline")=>{const c=supabase;if(!c||!athleteId)return;const{error}=kind==="join"?await c.rpc("join_club_challenge",{target_challenge_id:id,target_athlete_id:athleteId}):await c.rpc("respond_club_challenge",{target_challenge_id:id,target_athlete_id:athleteId,accept_invite:kind==="accept"});setNotice(error?error.message:"Actualizado.");if(!error)await load()};
 return <section className="club-challenge challenge-pro">
  <header className="challenge-pro-hero"><div><small>CLUB ATLETAS DE FUENLABRADA</small><h2>Challenge</h2><p>Entrena, reta a tus compañeros y celebra cada avance.</p></div><div className="challenge-pro-stat"><b>{weekly.reduce((n,r)=>n+km(r),0).toFixed(0)}</b><span>km esta semana</span></div></header>
  <nav className="challenge-pro-nav">{(["home","challenges","duels","ranking","achievements"] as const).map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v==="home"?"Inicio":v==="challenges"?"Retos":v==="duels"?"Duelos":v==="ranking"?"Clasificaciones":"Logros"}</button>)}{canCreate&&<button className="create" onClick={()=>setCreate(true)}>＋ Crear reto</button>}</nav>
  {notice&&<p className="challenge-notice">{notice}</p>}
  {create&&<form className="challenge-create" onSubmit={submit}><header><div><small>NUEVO DESAFÍO</small><h3>Crea algo que motive al equipo</h3></div><button type="button" className="outline" onClick={()=>setCreate(false)}>Cerrar</button></header><label>Nombre<input required maxLength={80} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Semana de constancia"/></label><label>Descripción<textarea maxLength={280} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Explica el objetivo y anima al grupo."/></label><div className="challenge-form-grid"><label>Modalidad<select value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="club">Todo el club</option><option value="group">Mi grupo</option>{athleteId&&<option value="duel">Duelo 1 contra 1</option>}</select></label><label>Clasificación<select value={createMetric} onChange={e=>{const m=e.target.value as Metric;setCreateMetric(m);setTarget(meta[m].target)}}>{Object.entries(meta).map(([k,x])=><option key={k} value={k}>{x.label}</option>)}</select></label><label>Meta<input type="number" min="1" required value={target} onChange={e=>setTarget(Number(e.target.value))}/><small>{meta[createMetric].unit}</small></label><label>Finaliza<input type="date" min={new Date().toISOString().slice(0,10)} required value={ends} onChange={e=>setEnds(e.target.value)}/></label>{scope==="duel"&&<label>Compañero<select required value={opponent} onChange={e=>setOpponent(e.target.value)}><option value="">Selecciona compañero</option>{opponents.map(r=><option key={r.athlete_id} value={r.athlete_id}>{r.first_name} {r.last_name}</option>)}</select></label>}</div><button>Publicar reto</button><p className="challenge-safety">La carga registrada compara constancia, no premia entrenamientos extremos.</p></form>}
  {view==="home"&&<><section className="challenge-dashboard"><article className="challenge-spotlight"><small>ESTA SEMANA</small><h3>{athleteId&&ranked.some(r=>r.athlete_id===athleteId)?`${ranked.findIndex(r=>r.athlete_id===athleteId)+1}º de ${ranked.length}`:"El club suma"}</h3><p>{athleteId?`${km(own).toFixed(1)} km acumulados esta temporada.`:"Cada actividad compartida hace avanzar al club."}</p><div className="challenge-progress"><i style={{width:`${Math.min(100,km(own)/5)}%`}}/></div></article><article className="challenge-streak"><span><ProIcon name="flame"/></span><div><small>RACHA PERSONAL</small><b>{streak} días</b><p>Tu mejor continuidad de la temporada.</p></div></article></section><Cards groups={grouped.filter(g=>g[0].scope!=="duel").slice(0,3)} athleteId={athleteId} act={act}/><Ranking rows={ranked.slice(0,6)} metric={metric}/></>}
  {view==="challenges"&&<><Heading over="OBJETIVOS COMPARTIDOS" title="Retos del club"/><Cards groups={grouped.filter(g=>g[0].scope!=="duel")} athleteId={athleteId} act={act}/>{!grouped.some(g=>g[0].scope!=="duel")&&<Empty text="Crea el primer reto para poner al equipo en marcha."/>}</>}
  {view==="duels"&&<><Heading over="1 CONTRA 1 · MISMO GRUPO" title="Duelos amistosos"/><Cards groups={grouped.filter(g=>g[0].scope==="duel")} athleteId={athleteId} act={act}/>{!grouped.some(g=>g[0].scope==="duel")&&<Empty text="Reta a un compañero de tu grupo."/>}</>}
  {view==="ranking"&&<><div className="challenge-ranking-controls"><div className="challenge-tabs"><button className={period==="week"?"selected-row":"outline"} onClick={()=>setPeriod("week")}>Esta semana</button><button className={period==="season"?"selected-row":"outline"} onClick={()=>setPeriod("season")}>Temporada</button></div><div className="challenge-metrics">{Object.entries(meta).map(([k,x])=><button key={k} className={metric===k?"active":""} onClick={()=>setMetric(k as Metric)}>{x.label}</button>)}</div></div><Ranking rows={ranked} metric={metric}/><p className="challenge-safety">La carga es una orientación lúdica basada en el dispositivo; nunca sustituye al entrenador ni es una recomendación médica.</p></>}
  {view==="achievements"&&<><Heading over="TU VITRINA" title="Logros y progreso"/><div className="achievement-grid pro-achievements">{[50,100,250,500,750,1000].map(x=><article className={`achievement ${km(own)>=x?"unlocked":"locked"}`} key={x}><span><ProIcon name="medal"/></span><b>{x} km</b><small>{km(own)>=x?"CONSEGUIDO":`${Math.min(100,km(own)/x*100).toFixed(0)}% completado`}</small></article>)}</div><div className="challenge-feed">{feed.map(x=><article key={`${x.athlete_id}-${x.achievement_key}`}><Avatar r={x}/><div><b>{x.title}</b><small>{x.first_name} {x.last_name}</small></div><time>{new Date(x.earned_at).toLocaleDateString("es-ES")}</time></article>)}</div></>}
 </section>
}

function Heading({over,title}:{over:string;title:string}){return <div className="challenge-section-head"><div><small>{over}</small><h2>{title}</h2></div></div>}
function Empty({text}:{text:string}){return <article className="challenge-empty"><span><ProIcon name="flag"/></span><h3>El próximo reto empieza aquí</h3><p>{text}</p></article>}
function Cards({groups,athleteId,act}:{groups:Progress[][];athleteId?:string;act:(id:string,k:"join"|"accept"|"decline")=>void}){return <div className="challenge-card-grid">{groups.map(ps=>{const c=ps[0],mine=ps.find(p=>p.athlete_id===athleteId),leader=[...ps].sort((a,b)=>Number(b.progress_value)-Number(a.progress_value))[0];return <article className="challenge-card" key={c.challenge_id}><header><span><ProIcon name={c.scope==="duel"?"duel":"flag"}/></span><div><small>{c.scope==="duel"?"DUELO":c.scope==="group"?"RETO DE GRUPO":"RETO DEL CLUB"}</small><h3>{c.title}</h3></div></header><p>{c.description||`Objetivo: ${value(Number(c.target_value),c.metric)}`}</p><div className="challenge-progress"><i style={{width:`${Math.min(100,Number(leader?.progress_value||0)/Number(c.target_value)*100)}%`}}/></div><div className="challenge-card-meta"><b>{value(Number(leader?.progress_value||0),c.metric)}</b><span>de {value(Number(c.target_value),c.metric)}</span><time>hasta {new Date(c.ends_on).toLocaleDateString("es-ES")}</time></div><div className="challenge-contenders">{ps.slice(0,5).map(p=><Avatar key={p.athlete_id} r={p}/>)}</div>{athleteId&&!mine&&c.scope!=="duel"&&<button onClick={()=>act(c.challenge_id,"join")}>Unirme</button>}{mine?.participant_status==="pending"&&<div className="inline-actions"><button onClick={()=>act(c.challenge_id,"accept")}>Aceptar duelo</button><button className="outline" onClick={()=>act(c.challenge_id,"decline")}>Rechazar</button></div>}</article>})}</div>}
function Ranking({rows,metric}:{rows:Row[];metric:Metric}){const max=Math.max(1,...rows.map(r=>score(r,metric)));return <article className="challenge-pro-ranking"><header><small>CLASIFICACIÓN · {meta[metric].label.toUpperCase()}</small><h2>El equipo en movimiento</h2></header>{rows.length?<><div className="challenge-podium">{rows.slice(0,3).map((r,i)=><div key={r.athlete_id} className={`place-${i+1}`}><Avatar r={r}/><b>{r.first_name}</b><strong>{value(score(r,metric),metric)}</strong><span>{i+1}º</span></div>)}</div><div className="challenge-rank-grid">{rows.slice(3,50).map((r,i)=><article key={r.athlete_id}><header><strong>{String(i+4).padStart(2,"0")}</strong><Avatar r={r}/><span><b>{r.first_name} {r.last_name}</b><small>{r.group_name||"Club"}</small></span></header><div><i style={{width:`${score(r,metric)/max*100}%`}}/></div><footer><span>{meta[metric].label}</span><b>{value(score(r,metric),metric)}</b></footer></article>)}</div></>:<p>Aún no hay actividad compartida.</p>}</article>}
