import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import "./coach-performance-overview.css";

type Group={id:string;name:string};
type Athlete={id:string;first_name:string;last_name:string;training_group_id:string|null};
type Activity={athlete_id:string;activity_type:string|null;started_at:string;moving_time_s:number|null;relative_effort:number|null};
type Feedback={athlete_id:string;session_date:string;duration_minutes:number|null;rpe:number|null;fatigue_feeling:number|null;pain_or_discomfort:boolean};
type RunnerState={athlete:Athlete;group:string;week:number;fitness:number;fatigue:number;form:number;lastDate:string|null;pain:boolean;hasData:boolean;status:"alert"|"watch"|"good"|"empty";label:string};
const runTypes=new Set(["run","trailrun","virtualrun","wheelchair"]);
const dateKey=(value:Date)=>value.toISOString().slice(0,10);

export default function CoachPerformanceOverview({profileId}:{profileId:string}){
  const [groups,setGroups]=useState<Group[]>([]),[athletes,setAthletes]=useState<Athlete[]>([]),[activities,setActivities]=useState<Activity[]>([]),[feedback,setFeedback]=useState<Feedback[]>([]),[avatars,setAvatars]=useState<Record<string,string>>({});
  const [loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{if(!supabase)return;void(async()=>{setLoading(true);setError("");const links=await supabase.from("training_group_coaches").select("training_groups(id,name)").eq("coach_profile_id",profileId);if(links.error){setError(links.error.message);setLoading(false);return}const running=((links.data||[]).map((row:any)=>row.training_groups).filter((group:any)=>group&&/running/i.test(group.name)) as Group[]);setGroups(running);if(!running.length){setLoading(false);return}const groupIds=running.map(group=>group.id);const athleteResponse=await supabase.from("athletes").select("id,first_name,last_name,training_group_id").in("training_group_id",groupIds).eq("club_status","active").order("last_name");const runnerRows=(athleteResponse.data||[]) as Athlete[];setAthletes(runnerRows);if(!runnerRows.length){setLoading(false);return}const ids=runnerRows.map(athlete=>athlete.id);const since=new Date();since.setDate(since.getDate()-90);const[a,f,p]=await Promise.all([supabase.from("external_sport_activities").select("athlete_id,activity_type,started_at,moving_time_s,relative_effort").in("athlete_id",ids).gte("started_at",since.toISOString()).order("started_at"),supabase.from("athlete_training_feedback").select("athlete_id,session_date,duration_minutes,rpe,fatigue_feeling,pain_or_discomfort").in("athlete_id",ids).gte("session_date",dateKey(since)).order("session_date"),supabase.from("athlete_profile_settings").select("athlete_id,avatar_url").in("athlete_id",ids)]);setActivities((a.data||[]) as Activity[]);setFeedback((f.data||[]) as Feedback[]);setAvatars(Object.fromEntries((p.data||[]).filter(item=>item.avatar_url).map(item=>[item.athlete_id,item.avatar_url])));setLoading(false)})()},[profileId]);
  const states=useMemo(()=>athletes.map(athlete=>{const ownActivities=activities.filter(item=>item.athlete_id===athlete.id&&runTypes.has(String(item.activity_type||"").toLowerCase()));const ownFeedback=feedback.filter(item=>item.athlete_id===athlete.id);const loads=new Map<string,number>();ownActivities.forEach(item=>{const day=item.started_at.slice(0,10),load=Number(item.relative_effort||0)||Number(item.moving_time_s||0)/60;loads.set(day,(loads.get(day)||0)+load)});ownFeedback.forEach(item=>{if(item.duration_minutes&&item.rpe)loads.set(item.session_date,Number(item.duration_minutes)*Number(item.rpe))});let fitness=0,fatigue=0;const start=new Date();start.setDate(start.getDate()-89);for(let i=0;i<90;i++){const day=new Date(start);day.setDate(start.getDate()+i);const load=loads.get(dateKey(day))||0;fitness+=(load-fitness)/42;fatigue+=(load-fatigue)/7}const form=fitness-fatigue;const weekStart=new Date();weekStart.setDate(weekStart.getDate()-6);const week=[...loads].filter(([day])=>day>=dateKey(weekStart)).reduce((sum,[,load])=>sum+load,0);const dates=[...ownActivities.map(item=>item.started_at.slice(0,10)),...ownFeedback.map(item=>item.session_date)].sort();const lastDate=dates.at(-1)||null;const pain=ownFeedback.slice(-14).some(item=>item.pain_or_discomfort);const inactive=!lastDate||Date.now()-new Date(`${lastDate}T12:00:00`).getTime()>14*86400000;const hasData=dates.length>0;let status:RunnerState["status"]="good",label="Equilibrado";if(!hasData){status="empty";label="Sin datos"}else if(pain||form<-22){status="alert";label=pain?"Molestia comunicada":"Fatiga alta"}else if(form<-10||inactive){status="watch";label=inactive?"Sin actividad reciente":"Vigilar carga"}return{athlete,group:groups.find(group=>group.id===athlete.training_group_id)?.name||"Running",week,fitness,fatigue,form,lastDate,pain,hasData,status,label}}).sort((a,b)=>({alert:0,watch:1,good:2,empty:3}[a.status]-{alert:0,watch:1,good:2,empty:3}[b.status])||a.athlete.last_name.localeCompare(b.athlete.last_name,"es")),[athletes,activities,feedback,groups]);
  const counters={alert:states.filter(item=>item.status==="alert").length,watch:states.filter(item=>item.status==="watch").length,good:states.filter(item=>item.status==="good").length,empty:states.filter(item=>item.status==="empty").length};
  return <section className="coach-performance"><header className="coach-performance-hero"><div><small>SPORTMED PERFORMANCE · RUNNING</small><h1>Rendimiento del equipo</h1><p>Una lectura rápida de carga, fatiga y alertas de todos tus runners.</p></div><div className="coach-performance-pulse"><b>{states.length}</b><span>runners</span></div></header><div className="coach-performance-summary"><article className="danger"><small>REVISAR HOY</small><b>{counters.alert}</b><span>Fatiga alta o molestias</span></article><article className="watch"><small>SEGUIMIENTO</small><b>{counters.watch}</b><span>Carga o actividad a vigilar</span></article><article className="good"><small>EQUILIBRADOS</small><b>{counters.good}</b><span>Sin alertas actuales</span></article><article><small>SIN DATOS</small><b>{counters.empty}</b><span>Pendientes de sincronizar</span></article></div>{loading?<article className="coach-performance-empty">Preparando el estado del equipo…</article>:error?<p className="error-note">No se pudo cargar el rendimiento: {error}</p>:!groups.length?<article className="coach-performance-empty"><h2>No tienes grupos Running asignados</h2><p>Esta herramienta aparece únicamente para los entrenadores responsables de Running.</p></article>:<div className="coach-performance-list">{states.map(item=><a key={item.athlete.id} className={`coach-runner-card ${item.status}`} href={`/deportivo?athleteId=${encodeURIComponent(item.athlete.id)}`}><div className="coach-runner-person">{avatars[item.athlete.id]?<img src={avatars[item.athlete.id]} alt=""/>:<i>{item.athlete.first_name[0]}{item.athlete.last_name[0]}</i>}<span><b>{item.athlete.first_name} {item.athlete.last_name}</b><small>{item.group}</small></span></div><span className="coach-runner-state"><i/>{item.label}</span><div className="coach-runner-metrics"><span><small>CARGA 7 DÍAS</small><b>{item.week.toFixed(0)}</b></span><span><small>FORMA</small><b>{item.hasData?item.fitness.toFixed(0):"—"}</b></span><span><small>FRESCURA</small><b>{item.hasData?`${item.form>0?"+":""}${item.form.toFixed(0)}`:"—"}</b></span></div><em>Ver análisis →</em></a>)}{!states.length&&<article className="coach-performance-empty"><h2>No hay runners activos</h2><p>Cuando haya atletas activos en tus grupos Running aparecerán aquí.</p></article>}</div>}<footer className="coach-performance-note">Datos orientativos para seguimiento deportivo. Las molestias requieren conversación directa con el atleta y no constituyen un diagnóstico.</footer></section>;
}
