import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Profile={id:string;email:string;full_name:string|null;phone?:string|null};
type Group={id:string;name:string;category_label:string;colour:string;schedule_days?:string|null;starts_at?:string|null;ends_at?:string|null};
type Athlete={id:string;first_name:string;last_name:string;club_status:string;license_status:string;license_number:string|null;training_group_id:string|null};
const monday=()=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)};

function useCoachData(profileId:string){const [groups,setGroups]=useState<Group[]>([]);const [athletes,setAthletes]=useState<Athlete[]>([]);const [plans,setPlans]=useState<any[]>([]);const [competitions,setCompetitions]=useState<any[]>([]);const [sessions,setSessions]=useState<any[]>([]);useEffect(()=>{if(!supabase)return;void Promise.all([supabase.from("training_group_coaches").select("training_groups(id,name,category_label,colour,schedule_days,starts_at,ends_at)").eq("coach_profile_id",profileId),supabase.from("athletes").select("id,first_name,last_name,club_status,license_status,license_number,training_group_id"),supabase.from("training_plans").select("id,title,week_starts_on,training_group_id").gte("week_starts_on",monday()),supabase.from("competition_events").select("id,title,starts_at,venue").gte("starts_at",new Date().toISOString()).order("starts_at").limit(5),supabase.from("attendance_sessions").select("id,training_group_id,starts_at").gte("starts_at",new Date().toISOString()).order("starts_at").limit(10)]).then(([links,a,p,c,s])=>{const own=(links.data||[]).map((x:any)=>x.training_groups).filter(Boolean);setGroups(own);const ids=new Set(own.map((g:any)=>g.id));setAthletes(((a.data||[]) as Athlete[]).filter(x=>x.training_group_id&&ids.has(x.training_group_id)));setPlans(p.data||[]);setCompetitions(c.data||[]);setSessions(s.data||[])})},[profileId]);return{groups,athletes,plans,competitions,sessions}}

export function CoachHome({profile,go}:{profile:Profile;go:(section:string)=>void}){const d=useCoachData(profile.id);const next=d.competitions[0];return <><div className="page-head"><div><h1>Hola, {profile.full_name?.split(" ")[0]||"entrenador"}</h1><p>Tu panel de trabajo para hoy.</p></div></div><section className="metric-grid"><button className="metric" onClick={()=>go(d.groups.length===1?"Mi grupo":"Mis grupos")}><small>Grupos asignados</small><b>{d.groups.length}</b><small>{d.athletes.length} atletas</small></button><button className="metric" onClick={()=>go("Planificación")}><small>Planes esta semana</small><b>{d.plans.length}</b><small>Publicados</small></button><button className="metric" onClick={()=>go("Asistencia")}><small>Sesiones próximas</small><b>{d.sessions.length}</b><small>Por gestionar</small></button></section><section className="two-columns"><article className="panel"><small>PRÓXIMA COMPETICIÓN</small><h2>{next?.title||"Sin competiciones próximas"}</h2><p>{next?`${new Date(next.starts_at).toLocaleString("es-ES")} · ${next.venue||"Lugar pendiente"}`:"Cuando se publique una carrera aparecerá aquí."}</p><button onClick={()=>go("Carreras")}>Abrir carreras</button></article><article className="panel"><small>ACCESOS RÁPIDOS</small><h2>¿Qué necesitas hacer?</h2><div className="inline-actions"><button onClick={()=>go("Asistencia")}>Pasar asistencia</button><button className="outline" onClick={()=>go("Planificación")}>Publicar plan</button><button className="outline" onClick={()=>go("Avisos")}>Escribir mensaje</button></div></article></section></>}

export function CoachGroups({profile}:{profile:Profile}){const d=useCoachData(profile.id);const [selected,setSelected]=useState("");const group=d.groups.find(g=>g.id===selected);const roster=d.athletes.filter(a=>a.training_group_id===selected);return <><div className="page-head"><div><h1>{d.groups.length===1?"Mi grupo":"Mis grupos"}</h1><p>Abre un grupo y después entra en la ficha deportiva de cada atleta.</p></div></div><section className="cards">{d.groups.map(g=><button className={`panel group-card group-button ${selected===g.id?"selected-row":""}`} key={g.id} onClick={()=>setSelected(g.id)}><i style={{background:g.colour}}/><h2>{g.name}</h2><p>{g.category_label}</p><small>{g.schedule_days||"Horario pendiente"}{g.starts_at?` · ${g.starts_at.slice(0,5)}–${g.ends_at?.slice(0,5)}`:""}</small></button>)}</section>{group&&<article className="panel table"><h2>{group.name} · {roster.length} atletas</h2>{roster.map(a=><a className="row athlete-row" key={a.id} href={`/deportivo?athleteId=${encodeURIComponent(a.id)}`}><span><b>{a.first_name} {a.last_name}</b><small>{a.club_status==="active"?"Activo":"En revisión"}</small></span><span>Licencia: {a.license_status==="active"?a.license_number||"activa":"pendiente"}</span><span>Ficha, marcas y mensajes →</span></a>)}{!roster.length&&<p>Este grupo todavía no tiene atletas visibles.</p>}</article>}</>}

export function CoachProfile({profile}:{profile:Profile}){const [form,setForm]=useState({full_name:profile.full_name||"",phone:profile.phone||"",bio:"",public_phone:"",avatar_url:"",cover_url:""});const [avatar,setAvatar]=useState<File|null>(null);const [cover,setCover]=useState<File|null>(null);const [notice,setNotice]=useState("");useEffect(()=>{if(!supabase)return;void supabase.from("coach_profile_settings").select("*").eq("profile_id",profile.id).maybeSingle().then(({data})=>{if(data)setForm(current=>({...current,...data}))})},[profile.id]);const upload=async(file:File,kind:string)=>{const path=`${profile.id}/coach-${kind}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase!.storage.from("athlete-profiles").upload(path,file);if(error)throw error;return supabase!.storage.from("athlete-profiles").getPublicUrl(path).data.publicUrl};const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;try{const avatar_url=avatar?await upload(avatar,"avatar"):form.avatar_url;const cover_url=cover?await upload(cover,"cover"):form.cover_url;const p=await supabase.from("profiles").update({full_name:form.full_name,phone:form.phone}).eq("id",profile.id);if(p.error)throw p.error;const s=await supabase.from("coach_profile_settings").upsert({profile_id:profile.id,bio:form.bio,public_phone:form.public_phone,avatar_url,cover_url,updated_at:new Date().toISOString()});if(s.error)throw s.error;setForm({...form,avatar_url,cover_url});setNotice("Perfil guardado correctamente.")}catch(error){setNotice(error instanceof Error?error.message:"No se pudo guardar el perfil.")}};return <><div className="page-head"><div><h1>Mi perfil</h1><p>Personaliza la información que verá el club.</p></div></div><form className="panel coach-profile-editor" onSubmit={save}><div className="athlete-cover" style={form.cover_url?{backgroundImage:`url(${form.cover_url})`}:undefined}>{form.avatar_url?<img className="athlete-avatar" src={form.avatar_url} alt="Foto del entrenador"/>:<span className="athlete-avatar athlete-avatar-placeholder">{(form.full_name||profile.email).slice(0,2).toUpperCase()}</span>}</div><div className="ops-grid"><label>Nombre público<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Teléfono de contacto<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Foto de perfil<input type="file" accept="image/*" onChange={e=>setAvatar(e.target.files?.[0]||null)}/></label><label>Foto de fondo<input type="file" accept="image/*" onChange={e=>setCover(e.target.files?.[0]||null)}/></label></div><label>Presentación<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} placeholder="Especialidad, experiencia o una breve presentación."/></label><button>Guardar mi perfil</button>{notice&&<p className={notice.startsWith("Perfil")?"success-note":"error-note"}>{notice}</p>}</form></>}
