import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type Profile={id:string;full_name:string|null};
type Group={id:string;name:string};
type SessionRow={id:string;training_group_id:string;starts_at:string};
type Competition={id:string;title:string;starts_at:string;venue:string|null};

const fmtTime=(value:string)=>new Date(value).toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"});
const dayLabel=(value:string)=>new Date(value).toLocaleDateString("es-ES",{day:"2-digit",month:"short"}).replace(".","");

export default function CoachHomeNext({profile,go}:{profile:Profile;go:(section:string)=>void}){
  const[groups,setGroups]=useState<Group[]>([]),[athletes,setAthletes]=useState<any[]>([]),[sessions,setSessions]=useState<SessionRow[]>([]),[plans,setPlans]=useState<any[]>([]),[competitions,setCompetitions]=useState<Competition[]>([]),[messages,setMessages]=useState<any[]>([]);
  useEffect(()=>{if(!supabase)return;void(async()=>{const links=await supabase.from("training_group_coaches").select("training_groups(id,name)").eq("coach_profile_id",profile.id);const own=(links.data||[]).map((row:any)=>row.training_groups).filter(Boolean) as Group[];setGroups(own);const ids=own.map(group=>group.id);if(!ids.length)return;const now=new Date().toISOString();const[a,s,p,c,m]=await Promise.all([supabase.from("athletes").select("id,training_group_id").in("training_group_id",ids),supabase.from("attendance_sessions").select("id,training_group_id,starts_at").in("training_group_id",ids).gte("starts_at",now).order("starts_at").limit(8),supabase.from("training_plans").select("id,training_group_id,published_at").in("training_group_id",ids).order("published_at",{ascending:false}).limit(8),supabase.from("competition_events").select("id,title,starts_at,venue").gte("starts_at",now).order("starts_at").limit(3),supabase.from("coach_athlete_messages").select("id,subject,created_at,training_group_id").in("training_group_id",ids).order("created_at",{ascending:false}).limit(3)]);setAthletes(a.data||[]);setSessions((s.data||[]) as SessionRow[]);setPlans(p.data||[]);setCompetitions((c.data||[]) as Competition[]);setMessages(m.data||[])})()},[profile.id]);
  const next=sessions[0],nextGroup=groups.find(group=>group.id===next?.training_group_id),todayKey=new Date().toLocaleDateString("en-CA");
  const today=useMemo(()=>sessions.filter(item=>new Date(item.starts_at).toLocaleDateString("en-CA")===todayKey),[sessions,todayKey]);
  const first=profile.full_name?.split(" ")[0]||"entrenador";
  return <section className="coach-next-home">
    <header className="coach-next-greeting"><div><small>PANEL DEL ENTRENADOR</small><h1>Hola, {first}.</h1><p>Hoy el club empieza contigo.</p></div><div className="coach-next-date"><b>{new Date().toLocaleDateString("es-ES",{weekday:"long"})}</b><span>{new Date().toLocaleDateString("es-ES",{day:"numeric",month:"long"})}</span></div></header>
    <article className="coach-next-hero">
      <div className="coach-next-hero-copy"><small>PRÓXIMA SESIÓN</small><h2>{nextGroup?`${nextGroup.name} sale a pista`:`Hoy no tienes sesiones`}</h2><p>{next?`${athletes.filter(a=>a.training_group_id===next.training_group_id).length} atletas · ${fmtTime(next.starts_at)} · Pista municipal`:"El calendario escolar no marca actividad para tus grupos."}</p><div className="coach-next-actions"><button onClick={()=>go("Asistencia")}>✓&nbsp; Pasar asistencia</button><button onClick={()=>go("Planificación")}>Ver plan</button></div></div>
      <div className="coach-next-track" aria-hidden="true"><i/><i/><i/><i/><div><small>{next?fmtTime(next.starts_at):"—"}</small><b>{nextGroup?.name||"Sin actividad"}</b></div></div>
    </article>
    <section className="coach-next-stats"><button onClick={()=>go(groups.length===1?"Mi grupo":"Mis grupos")}><small>ATLETAS</small><b>{athletes.length}</b><span>en {groups.length} grupo{groups.length===1?"":"s"}</span></button><button onClick={()=>go("Asistencia")}><small>SESIONES</small><b>{sessions.length}</b><span>próximas</span></button><button onClick={()=>go("Planificación")}><small>PLANES</small><b>{plans.length}</b><span>publicados</span></button><button onClick={()=>go("Carreras")}><small>COMPETICIONES</small><b>{competitions.length}</b><span>en agenda</span></button></section>
    <section className="coach-next-columns"><article className="coach-next-panel"><header><h3>Tu agenda</h3><button onClick={()=>go("Carreras")}>Ver calendario</button></header>{today.length?today.map(item=><div className="coach-next-agenda" key={item.id}><time>{fmtTime(item.starts_at)}</time><span><b>{groups.find(group=>group.id===item.training_group_id)?.name||"Grupo"}</b><small>Sesión de entrenamiento · Pista</small></span><em>→</em></div>):<div className="coach-next-empty">No hay más sesiones programadas para hoy.</div>}{competitions.slice(0,2).map(item=><div className="coach-next-agenda" key={item.id}><time>{dayLabel(item.starts_at)}</time><span><b>{item.title}</b><small>{item.venue||"Lugar pendiente"}</small></span><em>→</em></div>)}</article><article className="coach-next-panel"><header><h3>El club se mueve</h3><button onClick={()=>go("Avisos")}>Ver avisos</button></header>{messages.length?messages.map(item=><div className="coach-next-feed" key={item.id}><i>↗</i><span><b>{item.subject}</b><small>{new Date(item.created_at).toLocaleString("es-ES")}</small></span></div>):<><div className="coach-next-feed"><i>✓</i><span><b>Todo preparado</b><small>Los avisos del equipo aparecerán aquí.</small></span></div><div className="coach-next-feed"><i>⚡</i><span><b>{plans.length} planes activos</b><small>Consulta la planificación semanal.</small></span></div></>}</article></section>
  </section>;
}
