import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Profile={id:string;full_name:string|null}; type Group={id:string;name:string};
type Session={id:string;training_group_id:string;starts_at:string}; type Plan={id:string;training_group_id:string;title:string;body:string;week_starts_on:string;published_at:string}; type Message={id:string;subject:string;created_at:string};
type PlanDay={day:string;load:string;sections:{label:string;value:string}[]};

const parseWeeklyPlan=(body:string):PlanDay[]=>body.split(/\n\n(?=(?:LUNES|MARTES|MIÉRCOLES|JUEVES|VIERNES|SÁBADO|DOMINGO)\n)/).map(block=>{const lines=block.split("\n").filter(Boolean),day=lines.shift()||"";if(!/^(LUNES|MARTES|MIÉRCOLES|JUEVES|VIERNES|SÁBADO|DOMINGO)$/.test(day))return null;const load=lines.shift()||"",sections=lines.map(line=>{const separator=line.indexOf(":");return separator>0?{label:line.slice(0,separator),value:line.slice(separator+1).trim()}:{label:"Detalle",value:line}});return{day:day.charAt(0)+day.slice(1).toLowerCase(),load,sections}}).filter((item):item is PlanDay=>Boolean(item));

export default function CoachHomeNext({profile,go}:{profile:Profile;go:(section:string)=>void}){
 const[groups,setGroups]=useState<Group[]>([]),[athletes,setAthletes]=useState<{id:string;training_group_id:string}[]>([]),[sessions,setSessions]=useState<Session[]>([]),[plans,setPlans]=useState<Plan[]>([]),[messages,setMessages]=useState<Message[]>([]),[weeklyAttendance,setWeeklyAttendance]=useState<number[]>([0,0,0,0,0,0,0]),[activeGroup,setActiveGroup]=useState(""),[activePlanDay,setActivePlanDay]=useState(0);
 useEffect(()=>{if(!supabase)return;void(async()=>{const{data:links}=await supabase.from("training_group_coaches").select("training_groups(id,name)").eq("coach_profile_id",profile.id);const own=(links||[]).map((row:any)=>row.training_groups).filter(Boolean) as Group[];setGroups(own);setActiveGroup(current=>current||own[0]?.id||"");const ids=own.map(group=>group.id);if(!ids.length)return;const now=new Date(),weekStart=new Date(now);weekStart.setHours(0,0,0,0);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));const weekEnd=new Date(weekStart);weekEnd.setDate(weekStart.getDate()+7);const[a,s,p,m,weekSessions]=await Promise.all([supabase.from("athletes").select("id,training_group_id").in("training_group_id",ids),supabase.from("attendance_sessions").select("id,training_group_id,starts_at").in("training_group_id",ids).gte("starts_at",new Date().toISOString()).order("starts_at").limit(200),supabase.from("training_plans").select("id,training_group_id,title,body,week_starts_on,published_at").in("training_group_id",ids).not("published_at","is",null).order("published_at",{ascending:false}).limit(200),supabase.from("coach_athlete_messages").select("id,subject,created_at").in("training_group_id",ids).order("created_at",{ascending:false}).limit(3),supabase.from("attendance_sessions").select("id,starts_at").in("training_group_id",ids).gte("starts_at",weekStart.toISOString()).lt("starts_at",weekEnd.toISOString())]);setAthletes(a.data||[]);setSessions((s.data||[]) as Session[]);setPlans((p.data||[]) as Plan[]);setMessages((m.data||[]) as Message[]);const weekly=(weekSessions.data||[]) as {id:string;starts_at:string}[];if(weekly.length){const{data:attendance}=await supabase.from("attendance_records").select("session_id,attended").in("session_id",weekly.map(item=>item.id)).eq("attended",true);const counts=[0,0,0,0,0,0,0];for(const record of attendance||[]){const session=weekly.find(item=>item.id===record.session_id);if(session)counts[(new Date(session.starts_at).getDay()+6)%7]+=1}setWeeklyAttendance(counts)}else setWeeklyAttendance([0,0,0,0,0,0,0])})()},[profile.id]);
 const nextTrainingDay=sessions[0]?new Date(sessions[0].starts_at).toLocaleDateString("en-CA",{timeZone:"Europe/Madrid"}):null;
 const sessionCards=sessions.filter(session=>new Date(session.starts_at).toLocaleDateString("en-CA",{timeZone:"Europe/Madrid"})===nextTrainingDay).filter((session,index,list)=>list.findIndex(item=>item.training_group_id===session.training_group_id)===index);
 const publishedPlans=groups.map(group=>({group,plan:plans.find(plan=>plan.training_group_id===group.id&&Boolean(plan.published_at))})).filter(item=>item.plan);
 const activePublishedPlan=publishedPlans.find(item=>item.group.id===activeGroup)?.plan||null,planDays=activePublishedPlan?parseWeeklyPlan(activePublishedPlan.body):[];
 const first=profile.full_name?.split(" ")[0]||"entrenador",date=new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",month:"long"}).format(new Date()),maxAttendance=Math.max(1,...weeklyAttendance),weeklyTotal=weeklyAttendance.reduce((sum,value)=>sum+value,0);
 return <section className="design-v2-stage coach-live-home"><header className="design-v2-hero"><div><small>PANEL DEL ENTRENADOR</small><h1>El entrenamiento<br/>empieza aquí.</h1><p>{date.charAt(0).toUpperCase()+date.slice(1)} · Fuenlabrada</p></div><div className="design-v2-track"/></header><section className="design-v2-float">
  <div className="design-v2-title"><div><small>HOLA, {first.toUpperCase()}</small><h2>Tu semana en movimiento</h2></div><button onClick={()=>go("Planificación")}>Planificación →</button></div>
  <article className="design-v2-trend"><div><small>ASISTENCIA DEL EQUIPO · ESTA SEMANA</small><b>{weeklyTotal} <em>asistencias</em></b><span>{athletes.length} atletas · {groups.length} grupo(s)</span></div><svg className="coach-attendance-chart" viewBox="0 0 520 155" role="img" aria-label={`Asistencias de lunes a domingo: ${weeklyAttendance.join(", ")}`}><line x1="12" y1="137" x2="508" y2="137" stroke="#d8e4f2" strokeWidth="2"/>{weeklyAttendance.map((value,index)=>{const height=value?Math.max(12,(value/maxAttendance)*112):4;return <g key={index}><rect x={22+index*70} y={137-height} width="38" height={height} rx="10" fill={value?"#256bc8":"#d9e5f3"}/><text x={41+index*70} y={Math.max(13,130-height)} textAnchor="middle" fill="#173e70" fontSize="13" fontWeight="800">{value}</text></g>})}</svg><div className="design-v2-days"><span>L</span><span>M</span><span>X</span><span>J</span><span>V</span><span>S</span><span>D</span></div></article>
  <header className="design-v2-section-head"><div><small>SESIONES</small><h2>Próximos entrenamientos</h2></div><button onClick={()=>go("Asistencia")}>Ver agenda →</button></header>
  <section className="design-v2-sessions">{sessionCards.map((session,index)=>{const group=groups.find(item=>item.id===session.training_group_id),plan=plans.find(item=>item.training_group_id===session.training_group_id),when=new Date(session.starts_at);return <article key={session.id}><i>{index===0?"PRÓXIMA":when.toLocaleDateString("es-ES",{weekday:"short"}).toUpperCase()}</i><small>{when.toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"})}</small><h3>{group?.name||"Grupo"}</h3><p>{when.toLocaleDateString("es-ES",{weekday:"long",day:"numeric",month:"short"})}</p><b>{plan?.title||"Sesión por preparar"}</b><footer><span>{athletes.filter(item=>item.training_group_id===session.training_group_id).length} atletas</span><button onClick={()=>go("Asistencia")} aria-label="Abrir asistencia">▶</button></footer></article>})}{!sessionCards.length&&<article><i>AGENDA</i><h3>Sin sesiones próximas</h3><p>Las siguientes sesiones aparecerán aquí.</p><footer><span>{athletes.length} atletas</span><button onClick={()=>go("Asistencia")}>＋</button></footer></article>}</section>
  <section className="design-v2-bottom"><article><header><div><small>MENSAJES DEL CLUB</small><h3>{messages.length?"Actividad reciente":"Todo al día"}</h3></div><button onClick={()=>go("Avisos")}>Ver todos</button></header>{messages.length?messages.map(item=><div key={item.id}><i>↗</i><span><b>{item.subject}</b><small>{new Date(item.created_at).toLocaleString("es-ES")}</small></span><em/></div>):<div><i>✓</i><span><b>No tienes mensajes pendientes</b><small>Los nuevos avisos aparecerán aquí.</small></span><em/></div>}</article><aside><button onClick={()=>go("Asistencia")}><i>✓</i><span>Pasar<br/>asistencia</span></button><button onClick={()=>go("Planificación")}><i>＋</i><span>Crear<br/>plan</span></button><button onClick={()=>go("Avisos")}><i>↗</i><span>Enviar<br/>aviso</span></button></aside></section>
  <section className="coach-home-weekly-plans"><header className="design-v2-section-head"><div><small>MIS GRUPOS</small><h2>Planes de entrenamiento</h2></div></header>{publishedPlans.length?<><nav className="coach-home-group-tabs">{publishedPlans.map(({group})=><button type="button" key={group.id} className={activeGroup===group.id?"active":""} onClick={()=>{setActiveGroup(group.id);setActivePlanDay(0)}}>{group.name}</button>)}</nav>{activePublishedPlan&&<article className="member-live-plan member-week-plan"><div><small>PLAN SEMANAL PUBLICADO</small><h2>{activePublishedPlan.title}</h2><span>Semana del {new Date(`${activePublishedPlan.week_starts_on}T12:00:00`).toLocaleDateString("es-ES")}</span>{planDays.length?<><nav className="member-plan-days">{planDays.map((item,index)=><button type="button" key={item.day} className={activePlanDay===index?"active":""} onClick={()=>setActivePlanDay(index)}><b>{item.day}</b></button>)}</nav><section className="member-plan-session"><header><div><small>SESIÓN</small><h3>{planDays[activePlanDay]?.day}</h3></div><span>{planDays[activePlanDay]?.load}</span></header><div>{planDays[activePlanDay]?.sections.map((section,index)=><article key={`${section.label}-${index}`}><small>{section.label.toUpperCase()}</small><p>{section.value}</p></article>)}</div></section></>:<section className="member-plan-session"><header><div><small>PLAN PUBLICADO</small><h3>Resumen semanal</h3></div></header><div><article><small>CONTENIDO</small><p>{activePublishedPlan.body}</p></article></div></section>}</div></article>}</>:<p className="coach-home-empty-plan">Todavía no hay planes publicados para tus grupos.</p>}</section>
 </section></section>;
}
