import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Profile={id:string;full_name:string|null}; type Group={id:string;name:string};
type Session={id:string;training_group_id:string;starts_at:string}; type Plan={id:string;training_group_id:string;title:string;published_at:string}; type Message={id:string;subject:string;created_at:string};

export default function CoachHomeNext({profile,go}:{profile:Profile;go:(section:string)=>void}){
 const[groups,setGroups]=useState<Group[]>([]),[athletes,setAthletes]=useState<{id:string;training_group_id:string}[]>([]),[sessions,setSessions]=useState<Session[]>([]),[plans,setPlans]=useState<Plan[]>([]),[messages,setMessages]=useState<Message[]>([]);
 useEffect(()=>{if(!supabase)return;void(async()=>{const{data:links}=await supabase.from("training_group_coaches").select("training_groups(id,name)").eq("coach_profile_id",profile.id);const own=(links||[]).map((row:any)=>row.training_groups).filter(Boolean) as Group[];setGroups(own);const ids=own.map(group=>group.id);if(!ids.length)return;const[a,s,p,m]=await Promise.all([supabase.from("athletes").select("id,training_group_id").in("training_group_id",ids),supabase.from("attendance_sessions").select("id,training_group_id,starts_at").in("training_group_id",ids).gte("starts_at",new Date().toISOString()).order("starts_at").limit(8),supabase.from("training_plans").select("id,training_group_id,title,published_at").in("training_group_id",ids).order("published_at",{ascending:false}).limit(8),supabase.from("coach_athlete_messages").select("id,subject,created_at").in("training_group_id",ids).order("created_at",{ascending:false}).limit(3)]);setAthletes(a.data||[]);setSessions((s.data||[]) as Session[]);setPlans((p.data||[]) as Plan[]);setMessages((m.data||[]) as Message[])})()},[profile.id]);
 const first=profile.full_name?.split(" ")[0]||"entrenador",date=new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",month:"long"}).format(new Date()),sessionCards=sessions.slice(0,3);
 return <section className="design-v2-stage coach-live-home"><header className="design-v2-hero"><div><small>PANEL DEL ENTRENADOR</small><h1>El entrenamiento<br/>empieza aquí.</h1><p>{date.charAt(0).toUpperCase()+date.slice(1)} · Fuenlabrada</p></div><div className="design-v2-track"/></header><section className="design-v2-float">
  <div className="design-v2-title"><div><small>HOLA, {first.toUpperCase()}</small><h2>Tu semana en movimiento</h2></div><button onClick={()=>go("Planificación")}>Planificación →</button></div>
  <article className="design-v2-trend"><div><small>ACTIVIDAD DEL EQUIPO</small><b>{athletes.length} <em>atletas</em></b><span>{groups.length} grupo(s) bajo seguimiento</span></div><svg viewBox="0 0 520 155" aria-hidden="true"><defs><linearGradient id="coach-live-trend" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2b70d0" stopOpacity=".23"/><stop offset="1" stopColor="#2b70d0" stopOpacity="0"/></linearGradient></defs><path d="M0 123C45 112 52 64 99 78s60 39 102 12 51-73 99-42 56 79 102 47 71-66 118-51V155H0Z" fill="url(#coach-live-trend)"/><path d="M0 123C45 112 52 64 99 78s60 39 102 12 51-73 99-42 56 79 102 47 71-66 118-51" fill="none" stroke="#256bc8" strokeWidth="4" strokeLinecap="round"/></svg><div className="design-v2-days"><span>L</span><span>M</span><span>X</span><span>J</span><span>V</span><span>S</span><span>D</span></div></article>
  <header className="design-v2-section-head"><div><small>SESIONES</small><h2>Próximos entrenamientos</h2></div><button onClick={()=>go("Asistencia")}>Ver agenda →</button></header>
  <section className="design-v2-sessions">{sessionCards.map((session,index)=>{const group=groups.find(item=>item.id===session.training_group_id),plan=plans.find(item=>item.training_group_id===session.training_group_id),when=new Date(session.starts_at);return <article key={session.id}><i>{index===0?"PRÓXIMA":when.toLocaleDateString("es-ES",{weekday:"short"}).toUpperCase()}</i><small>{when.toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"})}</small><h3>{group?.name||"Grupo"}</h3><p>{when.toLocaleDateString("es-ES",{weekday:"long",day:"numeric",month:"short"})}</p><b>{plan?.title||"Sesión por preparar"}</b><footer><span>{athletes.filter(item=>item.training_group_id===session.training_group_id).length} atletas</span><button onClick={()=>go("Asistencia")} aria-label="Abrir asistencia">▶</button></footer></article>})}{!sessionCards.length&&<article><i>AGENDA</i><h3>Sin sesiones próximas</h3><p>Las siguientes sesiones aparecerán aquí.</p><footer><span>{athletes.length} atletas</span><button onClick={()=>go("Asistencia")}>＋</button></footer></article>}</section>
  <section className="design-v2-bottom"><article><header><div><small>MENSAJES DEL CLUB</small><h3>{messages.length?"Actividad reciente":"Todo al día"}</h3></div><button onClick={()=>go("Avisos")}>Ver todos</button></header>{messages.length?messages.map(item=><div key={item.id}><i>↗</i><span><b>{item.subject}</b><small>{new Date(item.created_at).toLocaleString("es-ES")}</small></span><em/></div>):<div><i>✓</i><span><b>No tienes mensajes pendientes</b><small>Los nuevos avisos aparecerán aquí.</small></span><em/></div>}</article><aside><button onClick={()=>go("Asistencia")}><i>✓</i><span>Pasar<br/>asistencia</span></button><button onClick={()=>go("Planificación")}><i>＋</i><span>Crear<br/>plan</span></button><button onClick={()=>go("Avisos")}><i>↗</i><span>Enviar<br/>aviso</span></button></aside></section>
 </section></section>;
}
