import { FormEvent, useState } from "react";
import { supabase } from "../lib/supabase";
import ConsentChecklist from "./ConsentChecklist";

type Athlete = {
  first_name: string; last_name: string; birth_date: string; federative_sex: "M" | "F"; dni_nie: string;
  relevant_condition: boolean; relevant_condition_detail: string; asthma_allergy_medication: string;
  injury_limitation: string; support_needs: string; health_notes: string;
};

const emptyAthlete = (): Athlete => ({first_name:"",last_name:"",birth_date:"",federative_sex:"M",dni_nie:"",relevant_condition:false,relevant_condition_detail:"",asthma_allergy_medication:"",injury_limitation:"",support_needs:"",health_notes:""});
export default function FamilyRegistration({email,onBack}:{email:string;onBack:()=>void}) {
  const [step,setStep]=useState(1); const [sent,setSent]=useState(false); const [error,setError]=useState(""); const [sending,setSending]=useState(false);
  const [guardian,setGuardian]=useState({relationship:"padre",first_name:"",last_name:"",dni_nie:"",phone:"",address_line:"",postal_code:"",locality:"",province:"Madrid",emergency_phone:""});
  const [athletes,setAthletes]=useState<Athlete[]>([emptyAthlete()]); const [plan,setPlan]=useState<"monthly"|"term">("monthly");
  const [consents,setConsents]=useState<Record<string,boolean>>({privacy:false,health_data:false,image_use:false,fam_data:false,club_rules:false,recurring_payment:false});
  const updateGuardian=(key:string,value:string)=>setGuardian(current=>({...current,[key]:value}));
  const updateAthlete=(index:number,key:keyof Athlete,value:string|boolean)=>setAthletes(current=>current.map((athlete,i)=>i===index?{...athlete,[key]:value}:athlete));
  const requiredGuardians=[guardian.first_name,guardian.last_name,guardian.dni_nie,guardian.phone,guardian.address_line,guardian.postal_code,guardian.locality,guardian.province].every(Boolean);
  const athletesReady=athletes.every(a=>a.first_name&&a.last_name&&a.birth_date&&a.federative_sex);
  const consentsReady=Object.values(consents).every(Boolean);
  const go=(next:number)=>{setError("");setStep(next)};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;if(!consentsReady){setError("Debes aceptar todos los consentimientos obligatorios.");return}setSending(true);setError("");const {error:rpcError}=await supabase.rpc("submit_family_registration",{payload:{...guardian,email,athletes,plan,consents:Object.keys(consents).filter(key=>consents[key])}});setSending(false);if(rpcError){setError(rpcError.message);return}setSent(true)};
  if(sent)return <main className="register-page"><section className="register-brand"><div className="brand"><i>AF</i><div><b>CLUB ATLETAS</b><small>DE FUENLABRADA</small></div></div><div><span>SOLICITUD RECIBIDA</span><h1>Gracias.<br/>Ya la revisamos.</h1><p>La licencia queda pendiente hasta que el club la tramite y asigne su número. No se hará ningún cargo todavía.</p></div></section><section className="register-form"><div className="form-wrap"><small className="step">PRÓXIMO PASO</small><h2>Validación administrativa</h2><p>El administrador revisará cada atleta. Cuando el proveedor de pago esté configurado recibirás el enlace seguro para vincular la tarjeta; nunca la escribes en esta aplicación.</p><button className="primary-wide" onClick={onBack}>Salir de la cuenta</button></div></section></main>;
  return <main className="register-page"><section className="register-brand"><div className="brand"><i>AF</i><div><b>CLUB ATLETAS</b><small>DE FUENLABRADA</small></div></div><div><span>ALTA DIGITAL · PASO {step} DE 4</span><h1>Tu inscripción,<br/>segura y completa.</h1><p>Cuenta: {email}. Podrás incluir a todos los atletas de la familia en una sola solicitud.</p></div><small>Club Atletas de Fuenlabrada · Temporada 2026/27</small></section><section className="register-form"><button className="back" onClick={onBack}>← Cerrar sesión</button><form className="form-wrap full-registration" onSubmit={submit}>
  {step===1&&<><small className="step">1 · DATOS DEL PADRE, MADRE O TUTOR</small><h2>Persona responsable</h2><p>Estos datos son obligatorios para registrar a un atleta menor de edad.</p><div className="field-grid"><label>Relación<select value={guardian.relationship} onChange={e=>updateGuardian("relationship",e.target.value)}><option value="padre">Padre</option><option value="madre">Madre</option><option value="tutor_legal">Tutor legal</option></select></label><label>DNI / NIE<input required value={guardian.dni_nie} onChange={e=>updateGuardian("dni_nie",e.target.value)}/></label><label>Nombre<input required value={guardian.first_name} onChange={e=>updateGuardian("first_name",e.target.value)}/></label><label>Apellidos<input required value={guardian.last_name} onChange={e=>updateGuardian("last_name",e.target.value)}/></label><label className="wide">Correo de la cuenta<input disabled value={email}/></label><label>Teléfono móvil<input required type="tel" value={guardian.phone} onChange={e=>updateGuardian("phone",e.target.value)}/></label><label>Teléfono de emergencia<input type="tel" value={guardian.emergency_phone} onChange={e=>updateGuardian("emergency_phone",e.target.value)}/></label><label className="wide">Domicilio<input required value={guardian.address_line} onChange={e=>updateGuardian("address_line",e.target.value)}/></label><label>Código postal<input required value={guardian.postal_code} onChange={e=>updateGuardian("postal_code",e.target.value)}/></label><label>Localidad<input required value={guardian.locality} onChange={e=>updateGuardian("locality",e.target.value)}/></label><label>Provincia<input required value={guardian.province} onChange={e=>updateGuardian("province",e.target.value)}/></label></div><button type="button" disabled={!requiredGuardians} className="primary-wide" onClick={()=>go(2)}>Continuar con los atletas →</button></>}
  {step===2&&<><small className="step">2 · DATOS DE LOS ATLETAS</small><h2>¿A quién inscribes?</h2><p>La licencia siempre queda pendiente hasta que el club la tramite. Puedes añadir varios atletas.</p>{athletes.map((athlete,index)=><fieldset className="athlete-block" key={index}><legend>Atleta {index+1}</legend><div className="field-grid"><label>Nombre<input required value={athlete.first_name} onChange={e=>updateAthlete(index,"first_name",e.target.value)}/></label><label>Apellidos<input required value={athlete.last_name} onChange={e=>updateAthlete(index,"last_name",e.target.value)}/></label><label>Fecha de nacimiento<input required type="date" value={athlete.birth_date} onChange={e=>updateAthlete(index,"birth_date",e.target.value)}/></label><label>Sexo federativo<select value={athlete.federative_sex} onChange={e=>updateAthlete(index,"federative_sex",e.target.value as "M"|"F")}><option value="M">Masculino</option><option value="F">Femenino</option></select></label><label className="wide">DNI / NIE <small>Opcional si aún no lo tiene</small><input value={athlete.dni_nie} onChange={e=>updateAthlete(index,"dni_nie",e.target.value)}/></label></div>{athletes.length>1&&<button type="button" className="remove-athlete" onClick={()=>setAthletes(current=>current.filter((_,i)=>i!==index))}>Quitar este atleta</button>}</fieldset>)}<button type="button" className="add-athlete" onClick={()=>setAthletes(current=>[...current,emptyAthlete()])}>＋ Añadir otro atleta</button><div className="form-actions"><button type="button" className="secondary" onClick={()=>go(1)}>Atrás</button><button type="button" disabled={!athletesReady} onClick={()=>go(3)}>Información de salud →</button></div></>}
  {step===3&&<><small className="step">3 · INFORMACIÓN DE SALUD</small><h2>Datos importantes para entrenar con seguridad</h2><p>Solo los administradores y el entrenador asignado podrán consultar esta información.</p>{athletes.map((athlete,index)=><fieldset className="athlete-block" key={index}><legend>{athlete.first_name||`Atleta ${index+1}`}</legend><label className="check-line"><input type="checkbox" checked={athlete.relevant_condition} onChange={e=>updateAthlete(index,"relevant_condition",e.target.checked)}/>¿Tiene alguna patología o información sanitaria relevante?</label><label>Detalle de patología, si procede<textarea value={athlete.relevant_condition_detail} onChange={e=>updateAthlete(index,"relevant_condition_detail",e.target.value)}/></label><label>Asma, alergias o medicación de rescate<textarea value={athlete.asthma_allergy_medication} onChange={e=>updateAthlete(index,"asthma_allergy_medication",e.target.value)}/></label><label>Lesiones o limitaciones para entrenar<textarea value={athlete.injury_limitation} onChange={e=>updateAthlete(index,"injury_limitation",e.target.value)}/></label><label>Necesidades de apoyo (por ejemplo, TDAH)<textarea value={athlete.support_needs} onChange={e=>updateAthlete(index,"support_needs",e.target.value)}/></label><label>Otra información que deba conocer el club<textarea value={athlete.health_notes} onChange={e=>updateAthlete(index,"health_notes",e.target.value)}/></label></fieldset>)}<div className="form-actions"><button type="button" className="secondary" onClick={()=>go(2)}>Atrás</button><button type="button" onClick={()=>go(4)}>Consentimientos y cuota →</button></div></>}
  {step===4&&<><small className="step">4 · CONSENTIMIENTOS Y CUOTA</small><h2>Antes de enviar la solicitud</h2><p>Abre cada documento con el símbolo ＋ para leer lo que aceptas. La aceptación queda registrada por atleta.</p><ConsentChecklist values={consents} onChange={(key,checked)=>setConsents(current=>({...current,[key]:checked}))}/><div className="plan-select"><b>Tipo de cuota</b><button type="button" aria-pressed={plan==="monthly"} className={plan==="monthly"?"chosen":""} onClick={()=>setPlan("monthly")}>Mensual · 35 €</button><button type="button" aria-pressed={plan==="term"} className={plan==="term"?"chosen":""} onClick={()=>setPlan("term")}>Trimestral · 70 €</button><small>El administrador revisa la matrícula, la proporcionalidad de alta y cualquier descuento familiar antes de aprobar el cobro.</small></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>go(3)}>Atrás</button><button disabled={!consentsReady||sending}>{sending?"Enviando…":"Enviar solicitud para revisión"}</button></div></>}
  </form></section></main>;
}
