import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type Draft={id:string;scheduled_for:string;approved_amount_cents:number|null;calculated_amount_cents:number;status:string;charge_kind:string};
type Entry={id:string;entry_type:"income"|"expense";status:"forecast"|"paid"|"cancelled";entry_date:string;category:string;concept:string;counterparty:string|null;amount_cents:number;payment_method:string;reference:string|null;notes:string|null;season:string};
const eur=(value:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(value/100);
const monthLabel=(key:string)=>new Intl.DateTimeFormat("es-ES",{month:"short",year:"2-digit"}).format(new Date(`${key}-01T12:00:00`));
const incomeCategories=["Subvención","Venta de ropa","Patrocinio","Donación","Actividad o evento","Otro ingreso"];
const expenseCategories=["Entrenadores y personal","Licencias federativas","Ropa y material","Página web y tecnología","Teléfono","Instalaciones","Desplazamientos","Gestoría e impuestos","Otro gasto"];
const methods=[['bank_transfer','Transferencia'],['cash','Efectivo'],['card','Tarjeta'],['direct_debit','Domiciliación'],['other','Otro']];

export default function FinancialControlCenter({drafts}:{drafts:Draft[]}){
 const [entries,setEntries]=useState<Entry[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [type,setType]=useState<"income"|"expense">("income"),[status,setStatus]=useState<"forecast"|"paid">("paid");
 const [form,setForm]=useState({entry_date:new Date().toISOString().slice(0,10),category:"Subvención",concept:"",counterparty:"",amount:"",payment_method:"bank_transfer",reference:"",notes:"",season:"2026-2027"});
 const load=async()=>{if(!supabase)return;setBusy(true);const {data,error}=await supabase.from("club_financial_entries").select("*").order("entry_date",{ascending:false});setEntries((data||[]) as Entry[]);setNotice(error?/club_financial_entries/.test(error.message)?"Activa la base financiera para empezar a registrar movimientos.":error.message:"");setBusy(false)};
 useEffect(()=>{void load()},[]);
 const live=entries.filter(e=>e.status!=="cancelled"), paidIncome=live.filter(e=>e.entry_type==="income"&&e.status==="paid").reduce((s,e)=>s+e.amount_cents,0),paidExpenses=live.filter(e=>e.entry_type==="expense"&&e.status==="paid").reduce((s,e)=>s+e.amount_cents,0);
 const feesPaid=drafts.filter(d=>d.status==="paid").reduce((s,d)=>s+(d.approved_amount_cents??d.calculated_amount_cents),0);
 const feeForecast=drafts.filter(d=>["awaiting_admin","approved","collecting","checkout_pending"].includes(d.status)).reduce((s,d)=>s+(d.approved_amount_cents??d.calculated_amount_cents),0);
 const otherForecast=live.filter(e=>e.entry_type==="income"&&e.status==="forecast").reduce((s,e)=>s+e.amount_cents,0),expenseForecast=live.filter(e=>e.entry_type==="expense"&&e.status==="forecast").reduce((s,e)=>s+e.amount_cents,0);
 const months=useMemo(()=>{const result=new Map<string,{fees:number,income:number,expense:number}>();const row=(key:string)=>{if(!result.has(key))result.set(key,{fees:0,income:0,expense:0});return result.get(key)!};drafts.filter(d=>d.status==="paid").forEach(d=>row(d.scheduled_for.slice(0,7)).fees+=d.approved_amount_cents??d.calculated_amount_cents);live.filter(e=>e.status==="paid").forEach(e=>row(e.entry_date.slice(0,7))[e.entry_type]+=e.amount_cents);return [...result.entries()].sort(([a],[b])=>a.localeCompare(b)).slice(-12)},[drafts,entries]);
 const max=Math.max(1,...months.flatMap(([,v])=>[v.fees+v.income,v.expense]));
 const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const cents=Math.round(Number(form.amount.replace(',','.'))*100);if(!Number.isFinite(cents)||cents<=0)return setNotice("Introduce un importe válido.");setBusy(true);const {error}=await supabase.from("club_financial_entries").insert({entry_type:type,status,entry_date:form.entry_date,category:form.category,concept:form.concept,counterparty:form.counterparty||null,amount_cents:cents,payment_method:form.payment_method,reference:form.reference||null,notes:form.notes||null,season:form.season});if(error){setNotice(error.message);setBusy(false);return}setForm({...form,concept:"",counterparty:"",amount:"",reference:"",notes:""});setNotice(type==="income"?"Ingreso registrado.":"Gasto registrado.");await load()};
 const remove=async(id:string)=>{if(!supabase||!window.confirm("¿Eliminar este movimiento financiero?"))return;await supabase.from("club_financial_entries").delete().eq("id",id);void load()};
 const exportCsv=()=>{const rows=[["Fecha","Tipo","Estado","Categoría","Concepto","Origen / proveedor","Método","Importe","Referencia","Temporada"],...entries.map(e=>[e.entry_date,e.entry_type==="income"?"Ingreso":"Gasto",e.status==="paid"?"Real":"Previsto",e.category,e.concept,e.counterparty||"",methods.find(m=>m[0]===e.payment_method)?.[1]||e.payment_method,(e.amount_cents/100).toFixed(2),e.reference||"",e.season])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`control-financiero-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <section className="finance-center">
  <section className="finance-metrics"><article><small>Ingresos reales</small><b>{eur(feesPaid+paidIncome)}</b><span>Cuotas {eur(feesPaid)} · Otros {eur(paidIncome)}</span></article><article><small>Gastos reales</small><b>{eur(paidExpenses)}</b><span>Pagados y contabilizados</span></article><article className={(feesPaid+paidIncome-paidExpenses)<0?"negative":"positive"}><small>Resultado real</small><b>{eur(feesPaid+paidIncome-paidExpenses)}</b><span>Ingresos menos gastos</span></article><article><small>Previsión neta</small><b>{eur(feeForecast+otherForecast-expenseForecast)}</b><span>Cuotas y movimientos previstos</span></article></section>
  <section className="finance-chart panel"><header><div><small>EVOLUCIÓN REAL</small><h2>Ingresos y gastos por mes</h2></div><div><span><i/>Ingresos</span><span><i/>Gastos</span></div></header>{months.length?<div className="finance-bars">{months.map(([key,value])=><div key={key}><section><i style={{height:`${Math.max(3,(value.fees+value.income)/max*100)}%`}} title={`Ingresos ${eur(value.fees+value.income)}`}/><i style={{height:`${Math.max(3,value.expense/max*100)}%`}} title={`Gastos ${eur(value.expense)}`}/></section><small>{monthLabel(key)}</small></div>)}</div>:<p>Aún no hay movimientos reales para dibujar la evolución.</p>}</section>
  <section className="finance-workspace">
   <form className="panel finance-entry" onSubmit={save}><header><div><small>NUEVO MOVIMIENTO</small><h2>Registrar ingreso o gasto</h2></div><nav><button type="button" className={type==="income"?"selected":""} onClick={()=>{setType("income");setForm({...form,category:"Subvención"})}}>+ Ingreso</button><button type="button" className={type==="expense"?"selected expense":""} onClick={()=>{setType("expense");setForm({...form,category:"Entrenadores y personal"})}}>− Gasto</button></nav></header><div className="finance-form-grid"><label>Fecha<input required type="date" value={form.entry_date} onChange={e=>setForm({...form,entry_date:e.target.value})}/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value as "forecast"|"paid")}><option value="paid">Real · ya cobrado/pagado</option><option value="forecast">Previsto</option></select></label><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{(type==="income"?incomeCategories:expenseCategories).map(c=><option key={c}>{c}</option>)}</select></label><label>Importe (€)<input required inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></label><label className="wide">Concepto<input required value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})} placeholder="Introduce el concepto"/></label><label>{type==="income"?"Origen o pagador":"Proveedor o destinatario"}<input value={form.counterparty} onChange={e=>setForm({...form,counterparty:e.target.value})} placeholder={type==="income"?"Introduce el pagador":"Introduce el proveedor o destinatario"}/></label><label>Método<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{methods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Referencia o justificante<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Introduce una referencia si existe"/></label><label>Temporada<input value={form.season} onChange={e=>setForm({...form,season:e.target.value})}/></label><label className="wide">Observaciones<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button disabled={busy}>Guardar {type==="income"?"ingreso":"gasto"}</button></form>
   <aside className="panel finance-summary"><small>PREVISIÓN</small><h2>Vista de temporada</h2><div><span>Cuotas pendientes<b>{eur(feeForecast)}</b></span><span>Otros ingresos previstos<b>{eur(otherForecast)}</b></span><span>Gastos previstos<b>− {eur(expenseForecast)}</b></span><span className="total">Resultado previsto<b>{eur(feeForecast+otherForecast-expenseForecast)}</b></span></div><button type="button" onClick={exportCsv}>Exportar para Excel</button><p>Incluye los movimientos manuales. Las cuotas de Stripe permanecen vinculadas automáticamente al panel.</p></aside>
  </section>
  {notice&&<p className={notice.includes("registrado")?"success-note panel":"error-note panel"}>{notice}</p>}
  <section className="panel table finance-ledger"><header><div><small>LIBRO DE MOVIMIENTOS</small><h2>Ingresos y gastos registrados</h2></div><button className="outline" onClick={exportCsv}>Exportar</button></header>{entries.map(e=><div className="row" key={e.id}><span><b>{e.concept}</b><small>{e.category} · {e.counterparty||"Sin origen/proveedor"}</small></span><span><small>{new Date(`${e.entry_date}T12:00:00`).toLocaleDateString("es-ES")}</small><b>{methods.find(m=>m[0]===e.payment_method)?.[1]}</b></span><span className={e.entry_type}><small>{e.status==="paid"?"Real":"Previsto"}</small><b>{e.entry_type==="expense"?"− ":"+ "}{eur(e.amount_cents)}</b></span><button className="outline" onClick={()=>void remove(e.id)}>Eliminar</button></div>)}{!entries.length&&<p className="empty">Aún no hay otros ingresos ni gastos registrados.</p>}</section>
 </section>
}
