import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type Draft={id:string;membership_id:string;scheduled_for:string;period_starts_on?:string|null;period_ends_on?:string|null;approved_amount_cents:number|null;calculated_amount_cents:number;status:string;charge_kind:string;memberships?:{plan?:string}|null};
type Entry={id:string;entry_type:"income"|"expense";status:"forecast"|"paid"|"cancelled";entry_date:string;category:string;concept:string;counterparty:string|null;amount_cents:number;payment_method:string;reference:string|null;notes:string|null;season:string};
type ClubAthlete={id:string;first_name:string;last_name:string;club_status:string};
type ClubMembership={id:string;athlete_id:string;plan:"monthly"|"term";billing_status:string};
const eur=(value:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(value/100);
const monthLabel=(key:string)=>new Intl.DateTimeFormat("es-ES",{month:"short",year:"2-digit"}).format(new Date(`${key}-01T12:00:00`));
const incomeCategories=["Subvención","Venta de ropa","Patrocinio","Donación","Actividad o evento","Otro ingreso"];
const expenseCategories=["Entrenadores y personal","Licencias federativas","Ropa y material","Página web y tecnología","Teléfono","Instalaciones","Desplazamientos","Gestoría e impuestos","Otro gasto"];
const methods=[['bank_transfer','Transferencia'],['cash','Efectivo'],['card','Tarjeta'],['direct_debit','Domiciliación'],['other','Otro']];
const chargeStatuses=new Set(["awaiting_admin","approved","collecting","checkout_pending","paid","failed"]);
const monthKeysBetween=(start:string,end:string)=>{const result:string[]=[];const cursor=new Date(`${start.slice(0,7)}-01T12:00:00`),limit=new Date(`${end.slice(0,7)}-01T12:00:00`);while(cursor<=limit&&result.length<12){result.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`);cursor.setMonth(cursor.getMonth()+1)}return result};
const coveredMonths=(draft:Draft)=>{if(draft.charge_kind!=="recurring"||draft.memberships?.plan!=="term")return [draft.scheduled_for.slice(0,7)];if(draft.period_starts_on&&draft.period_ends_on)return monthKeysBetween(draft.period_starts_on,draft.period_ends_on);const key=draft.scheduled_for.slice(0,7),month=Number(key.slice(5,7)),count=month===3?4:3;const start=new Date(`${key}-01T12:00:00`),end=new Date(start);end.setMonth(end.getMonth()+count-1);return monthKeysBetween(start.toISOString().slice(0,10),end.toISOString().slice(0,10))};

export default function FinancialControlCenter({drafts}:{drafts:Draft[]}){
 const [entries,setEntries]=useState<Entry[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [athletes,setAthletes]=useState<ClubAthlete[]>([]),[memberships,setMemberships]=useState<ClubMembership[]>([]);
 const [year,setYear]=useState(String(new Date().getFullYear())),[month,setMonth]=useState("all");
 const [accountingView,setAccountingView]=useState<"cash"|"accrual">("accrual");
 const [type,setType]=useState<"income"|"expense">("income"),[status,setStatus]=useState<"forecast"|"paid">("paid");
 const [form,setForm]=useState({entry_date:new Date().toISOString().slice(0,10),category:"Subvención",concept:"",counterparty:"",amount:"",payment_method:"bank_transfer",reference:"",notes:"",season:"2026-2027"});
 const load=async()=>{if(!supabase)return;setBusy(true);const [{data,error},{data:athleteData},{data:membershipData}]=await Promise.all([supabase.from("club_financial_entries").select("*").order("entry_date",{ascending:false}),supabase.from("athletes").select("id,first_name,last_name,club_status"),supabase.from("memberships").select("id,athlete_id,plan,billing_status")]);setEntries((data||[]) as Entry[]);setAthletes((athleteData||[]) as ClubAthlete[]);setMemberships((membershipData||[]) as ClubMembership[]);setNotice(error?/club_financial_entries/.test(error.message)?"Activa la base financiera para empezar a registrar movimientos.":error.message:"");setBusy(false)};
 useEffect(()=>{void load()},[]);
 const years=[...new Set([String(new Date().getFullYear()),...entries.map(e=>e.entry_date.slice(0,4)),...drafts.map(d=>d.scheduled_for.slice(0,4))])].sort((a,b)=>b.localeCompare(a));
 const inPeriod=(date:string)=>date.startsWith(year)&&(month==="all"||date.slice(5,7)===month);
 const periodEntries=entries.filter(e=>inPeriod(e.entry_date)),periodDrafts=drafts.filter(d=>inPeriod(d.scheduled_for));
 const live=periodEntries.filter(e=>e.status!=="cancelled"), paidIncome=live.filter(e=>e.entry_type==="income"&&e.status==="paid").reduce((s,e)=>s+e.amount_cents,0),paidExpenses=live.filter(e=>e.entry_type==="expense"&&e.status==="paid").reduce((s,e)=>s+e.amount_cents,0);
 const feesPaid=periodDrafts.filter(d=>d.status==="paid").reduce((s,d)=>s+(d.approved_amount_cents??d.calculated_amount_cents),0);
 const paidEnrolments=periodDrafts.filter(d=>d.charge_kind==="enrolment"&&d.status==="paid"&&(d.approved_amount_cents??d.calculated_amount_cents)>0),paidEnrolmentAmount=paidEnrolments.reduce((s,d)=>s+(d.approved_amount_cents??d.calculated_amount_cents),0);
 const feeForecast=periodDrafts.filter(d=>["awaiting_admin","approved","collecting","checkout_pending"].includes(d.status)).reduce((s,d)=>s+(d.approved_amount_cents??d.calculated_amount_cents),0);
 const otherForecast=live.filter(e=>e.entry_type==="income"&&e.status==="forecast").reduce((s,e)=>s+e.amount_cents,0),expenseForecast=live.filter(e=>e.entry_type==="expense"&&e.status==="forecast").reduce((s,e)=>s+e.amount_cents,0);
 const months=useMemo(()=>{const result=new Map<string,{fees:number,income:number,expense:number}>();const row=(key:string)=>{if(!result.has(key))result.set(key,{fees:0,income:0,expense:0});return result.get(key)!};drafts.filter(d=>d.status==="paid").forEach(d=>row(d.scheduled_for.slice(0,7)).fees+=d.approved_amount_cents??d.calculated_amount_cents);live.filter(e=>e.status==="paid").forEach(e=>row(e.entry_date.slice(0,7))[e.entry_type]+=e.amount_cents);return [...result.entries()].sort(([a],[b])=>a.localeCompare(b)).slice(-12)},[drafts,entries]);
 const max=Math.max(1,...months.flatMap(([,v])=>[v.fees+v.income,v.expense]));
 const accountingMonths=useMemo(()=>{const result=new Map<string,{cashFees:number;accruedFees:number;income:number;expense:number}>();const row=(key:string)=>{if(!result.has(key))result.set(key,{cashFees:0,accruedFees:0,income:0,expense:0});return result.get(key)!};drafts.filter(d=>chargeStatuses.has(d.status)&&d.charge_kind!=="manual").forEach(d=>{const amount=d.approved_amount_cents??d.calculated_amount_cents;row(d.scheduled_for.slice(0,7)).cashFees+=amount;const keys=coveredMonths(d),base=Math.floor(amount/keys.length),remainder=amount-base*keys.length;keys.forEach((key,index)=>row(key).accruedFees+=base+(index<remainder?1:0))});entries.filter(e=>e.status!=="cancelled").forEach(e=>row(e.entry_date.slice(0,7))[e.entry_type]+=e.amount_cents);return [...result.entries()].filter(([key])=>key.startsWith(year)).sort(([a],[b])=>a.localeCompare(b))},[drafts,entries,year]);
 const accountingPeriod=accountingMonths.filter(([key])=>month==="all"||key.slice(5,7)===month),accountingTotals=accountingPeriod.reduce((total,[,value])=>({cashFees:total.cashFees+value.cashFees,accruedFees:total.accruedFees+value.accruedFees,income:total.income+value.income,expense:total.expense+value.expense}),{cashFees:0,accruedFees:0,income:0,expense:0});
 const accountingIncome=(accountingView==="cash"?accountingTotals.cashFees:accountingTotals.accruedFees)+accountingTotals.income,accountingResult=accountingIncome-accountingTotals.expense;
 const activeAthletes=athletes.filter(a=>a.club_status==="active"),activeIds=new Set(activeAthletes.map(a=>a.id));
 const activeMemberships=memberships.filter(m=>activeIds.has(m.athlete_id)&&m.billing_status!=="cancelled");
 const coveredIds=new Set(activeMemberships.map(m=>m.athlete_id)),missingAthletes=activeAthletes.filter(a=>!coveredIds.has(a.id));
 const monthlyCount=new Set(activeMemberships.filter(m=>m.plan==="monthly").map(m=>m.athlete_id)).size,termCount=new Set(activeMemberships.filter(m=>m.plan==="term").map(m=>m.athlete_id)).size;
 const periodStart=month==="all"?`${year}-01`:`${year}-${month}`,periodEnd=month==="all"?`${year}-12`:`${year}-${month}`;
 const dueMemberships=activeMemberships.filter(m=>m.plan==="monthly"||month==="all"||["09","12","03"].includes(month));
 const draftMembershipIds=new Set(drafts.filter(d=>d.charge_kind==="recurring"&&d.scheduled_for.slice(0,7)>=periodStart&&d.scheduled_for.slice(0,7)<=periodEnd&&!['cancelled','waived'].includes(d.status)).map(d=>d.membership_id));
 const withoutScheduledCharge=dueMemberships.filter(m=>!draftMembershipIds.has(m.id));
 const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const cents=Math.round(Number(form.amount.replace(',','.'))*100);if(!Number.isFinite(cents)||cents<=0)return setNotice("Introduce un importe válido.");setBusy(true);const {error}=await supabase.from("club_financial_entries").insert({entry_type:type,status,entry_date:form.entry_date,category:form.category,concept:form.concept,counterparty:form.counterparty||null,amount_cents:cents,payment_method:form.payment_method,reference:form.reference||null,notes:form.notes||null,season:form.season});if(error){setNotice(error.message);setBusy(false);return}setForm({...form,concept:"",counterparty:"",amount:"",reference:"",notes:""});setNotice(type==="income"?"Ingreso registrado.":"Gasto registrado.");await load()};
 const remove=async(id:string)=>{if(!supabase||!window.confirm("¿Eliminar este movimiento financiero?"))return;await supabase.from("club_financial_entries").delete().eq("id",id);void load()};
 const exportCsv=()=>{const rows=[["Fecha","Tipo","Estado","Categoría","Concepto","Origen / proveedor","Método","Importe","Referencia","Temporada"],...periodEntries.map(e=>[e.entry_date,e.entry_type==="income"?"Ingreso":"Gasto",e.status==="paid"?"Real":"Previsto",e.category,e.concept,e.counterparty||"",methods.find(m=>m[0]===e.payment_method)?.[1]||e.payment_method,(e.amount_cents/100).toFixed(2),e.reference||"",e.season])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`control-financiero-${year}-${month}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <section className="finance-center">
  <nav className="finance-period"><div><small>PERIODO DEL INFORME</small><b>{month==="all"?`Año ${year}`:`${monthLabel(`${year}-${month}`)}`}</b></div><label>Año<select value={year} onChange={e=>setYear(e.target.value)}>{years.map(item=><option key={item}>{item}</option>)}</select></label><label>Mes<select value={month} onChange={e=>setMonth(e.target.value)}><option value="all">Todo el año</option>{Array.from({length:12},(_,index)=>String(index+1).padStart(2,'0')).map(value=><option key={value} value={value}>{new Intl.DateTimeFormat('es-ES',{month:'long'}).format(new Date(`2026-${value}-01T12:00:00`))}</option>)}</select></label></nav>
  <section className={`finance-coverage ${missingAthletes.length||withoutScheduledCharge.length?"has-errors":"is-complete"}`}><header><div><small>CONTROL DE COBERTURA</small><h2>{missingAthletes.length||withoutScheduledCharge.length?"Hay cuotas que requieren revisión":"Todos los atletas tienen cuota asignada"}</h2><p>Compara atletas activos, modalidad económica y cargos preparados para el periodo.</p></div><span>{missingAthletes.length+withoutScheduledCharge.length?`${missingAthletes.length+withoutScheduledCharge.length} avisos`:"✓ Cuadrado"}</span></header><div><article><small>Atletas activos</small><b>{activeAthletes.length}</b></article><article><small>Cuota mensual</small><b>{monthlyCount}</b></article><article><small>Cuota trimestral</small><b>{termCount}</b></article><article><small>Total con modalidad</small><b>{coveredIds.size} / {activeAthletes.length}</b></article><article><small>Cargos del periodo</small><b>{dueMemberships.length-withoutScheduledCharge.length} / {dueMemberships.length}</b></article></div>{(missingAthletes.length>0||withoutScheduledCharge.length>0)&&<aside>{missingAthletes.map(a=><span key={`member-${a.id}`}><b>{a.first_name} {a.last_name}</b><small>Sin cuota mensual ni trimestral vinculada</small></span>)}{withoutScheduledCharge.map(m=>{const a=activeAthletes.find(item=>item.id===m.athlete_id);return <span key={`charge-${m.id}`}><b>{a?`${a.first_name} ${a.last_name}`:"Atleta"}</b><small>Cuota {m.plan==="monthly"?"mensual":"trimestral"} sin cargo preparado en este periodo</small></span>})}</aside>}</section>
  <section className="finance-metrics"><article className="paid-enrolments-metric"><small>Matrículas cobradas</small><b>{paidEnrolments.length}</b><span>{eur(paidEnrolmentAmount)} · no incluye renovaciones a 0 €</span></article><article><small>Ingresos reales</small><b>{eur(feesPaid+paidIncome)}</b><span>Cuotas {eur(feesPaid)} · Otros {eur(paidIncome)}</span></article><article><small>Gastos reales</small><b>{eur(paidExpenses)}</b><span>Pagados y contabilizados</span></article><article className={(feesPaid+paidIncome-paidExpenses)<0?"negative":"positive"}><small>Resultado real</small><b>{eur(feesPaid+paidIncome-paidExpenses)}</b><span>Ingresos menos gastos</span></article><article><small>Previsión neta</small><b>{eur(feeForecast+otherForecast-expenseForecast)}</b><span>Cuotas y movimientos previstos</span></article></section>
  <section className="panel finance-accounting"><header><div><small>PREVISIÓN MENSUAL</small><h2>Caja o resultado contable</h2><p>Consulta cuándo entra el dinero o repártelo entre los meses realmente cubiertos por cada cuota.</p></div><nav><button type="button" className={accountingView==="cash"?"selected":""} onClick={()=>setAccountingView("cash")}>Caja · mes de cobro</button><button type="button" className={accountingView==="accrual"?"selected":""} onClick={()=>setAccountingView("accrual")}>Resultado mensual · repartido</button></nav></header><div className="finance-accounting-summary"><article><small>{accountingView==="cash"?"Cobros previstos":"Ingresos imputados"}</small><b>{eur(accountingIncome)}</b><span>{accountingView==="cash"?"Importe completo en la fecha de cobro":"Cuotas repartidas entre los meses que cubren"}</span></article><article><small>Gastos del periodo</small><b>{eur(accountingTotals.expense)}</b><span>Reales y previstos registrados</span></article><article className={accountingResult<0?"negative":"positive"}><small>Resultado previsto</small><b>{eur(accountingResult)}</b><span>{accountingView==="cash"?"Flujo de caja":"Pérdidas y ganancias mensual"}</span></article><article><small>Cobro efectivo en caja</small><b>{eur(accountingTotals.cashFees+accountingTotals.income)}</b><span>Referencia para tesorería</span></article></div><div className="finance-accounting-table"><div><b>Mes</b><b>Cobro en caja</b><b>Ingreso repartido</b><b>Gastos</b><b>Resultado mensual</b></div>{accountingPeriod.map(([key,value])=>{const income=value.accruedFees+value.income,result=income-value.expense;return <div key={key}><span>{monthLabel(key)}</span><span>{eur(value.cashFees+value.income)}</span><span>{eur(income)}</span><span>{eur(value.expense)}</span><strong className={result<0?"negative":"positive"}>{eur(result)}</strong></div>})}{!accountingPeriod.length&&<p>No hay cuotas ni movimientos previstos para este periodo.</p>}</div><footer><b>Criterio aplicado:</b> mensual y matrícula en un solo mes; septiembre–noviembre y diciembre–febrero en 3 meses; marzo–junio en 4 meses.</footer></section>
  <section className="finance-chart panel"><header><div><small>EVOLUCIÓN REAL</small><h2>Ingresos y gastos por mes</h2></div><div><span><i/>Ingresos</span><span><i/>Gastos</span></div></header>{months.length?<div className="finance-bars">{months.map(([key,value])=><div key={key}><section><i style={{height:`${Math.max(3,(value.fees+value.income)/max*100)}%`}} title={`Ingresos ${eur(value.fees+value.income)}`}/><i style={{height:`${Math.max(3,value.expense/max*100)}%`}} title={`Gastos ${eur(value.expense)}`}/></section><small>{monthLabel(key)}</small></div>)}</div>:<p>Aún no hay movimientos reales para dibujar la evolución.</p>}</section>
  <section className="finance-workspace">
   <form className="panel finance-entry" onSubmit={save}><header><div><small>NUEVO MOVIMIENTO</small><h2>Registrar ingreso o gasto</h2></div><nav><button type="button" className={type==="income"?"selected":""} onClick={()=>{setType("income");setForm({...form,category:"Subvención"})}}>+ Ingreso</button><button type="button" className={type==="expense"?"selected expense":""} onClick={()=>{setType("expense");setForm({...form,category:"Entrenadores y personal"})}}>− Gasto</button></nav></header><div className="finance-form-grid"><label>Fecha<input required type="date" value={form.entry_date} onChange={e=>setForm({...form,entry_date:e.target.value})}/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value as "forecast"|"paid")}><option value="paid">Real · ya cobrado/pagado</option><option value="forecast">Previsto</option></select></label><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{(type==="income"?incomeCategories:expenseCategories).map(c=><option key={c}>{c}</option>)}</select></label><label>Importe (€)<input required inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></label><label className="wide">Concepto<input required value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})} placeholder="Introduce el concepto"/></label><label>{type==="income"?"Origen o pagador":"Proveedor o destinatario"}<input value={form.counterparty} onChange={e=>setForm({...form,counterparty:e.target.value})} placeholder={type==="income"?"Introduce el pagador":"Introduce el proveedor o destinatario"}/></label><label>Método<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{methods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Referencia o justificante<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Introduce una referencia si existe"/></label><label>Temporada<input value={form.season} onChange={e=>setForm({...form,season:e.target.value})}/></label><label className="wide">Observaciones<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button disabled={busy}>Guardar {type==="income"?"ingreso":"gasto"}</button></form>
   <aside className="panel finance-summary"><small>PREVISIÓN</small><h2>Vista de temporada</h2><div><span>Cuotas pendientes<b>{eur(feeForecast)}</b></span><span>Otros ingresos previstos<b>{eur(otherForecast)}</b></span><span>Gastos previstos<b>− {eur(expenseForecast)}</b></span><span className="total">Resultado previsto<b>{eur(feeForecast+otherForecast-expenseForecast)}</b></span></div><button type="button" onClick={exportCsv}>Exportar para Excel</button><p>Incluye los movimientos manuales. Las cuotas de Stripe permanecen vinculadas automáticamente al panel.</p></aside>
  </section>
  {notice&&<p className={notice.includes("registrado")?"success-note panel":"error-note panel"}>{notice}</p>}
  <section className="panel table finance-ledger"><header><div><small>LIBRO DE MOVIMIENTOS</small><h2>Ingresos y gastos · {month==="all"?year:monthLabel(`${year}-${month}`)}</h2></div><button className="outline" onClick={exportCsv}>Exportar</button></header>{periodEntries.map(e=><div className="row" key={e.id}><span><b>{e.concept}</b><small>{e.category} · {e.counterparty||"Sin origen/proveedor"}</small></span><span><small>{new Date(`${e.entry_date}T12:00:00`).toLocaleDateString("es-ES")}</small><b>{methods.find(m=>m[0]===e.payment_method)?.[1]}</b></span><span className={e.entry_type}><small>{e.status==="paid"?"Real":"Previsto"}</small><b>{e.entry_type==="expense"?"− ":"+ "}{eur(e.amount_cents)}</b></span><button className="outline" onClick={()=>void remove(e.id)}>Eliminar</button></div>)}{!periodEntries.length&&<p className="empty">No hay otros ingresos ni gastos en este periodo.</p>}</section>
 </section>
}
