import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Charge = { id: string; athlete_id: string; charge_kind: "enrolment" | "recurring" | "manual"; approved_amount_cents: number | null; calculated_amount_cents: number; scheduled_for: string; period_starts_on: string | null; period_ends_on: string | null; status: string; calculation_snapshot?: { plan?: "monthly" | "term" } | null; athletes?: { first_name: string; last_name: string }[] | null };
const euro = (cents: number) => new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100);
const status = (value: string) => ({ awaiting_admin: "Pendiente de revisión", approved: "Programada", checkout_pending: "Pendiente de pago", paid: "Pagada", waived: "Exenta", cancelled: "Cancelada" } as Record<string, string>)[value] || value;

export default function MemberFees({ isDemo = false }: { isDemo?: boolean }) {
  const [charges, setCharges] = useState<Charge[]>([]); const [athleteNames, setAthleteNames] = useState<Record<string, string>>({}); const [open, setOpen] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { if (!supabase) return; const { data } = await supabase.from("billing_charge_drafts").select("id,athlete_id,charge_kind,approved_amount_cents,calculated_amount_cents,scheduled_for,period_starts_on,period_ends_on,status,calculation_snapshot,athletes(first_name,last_name)").order("scheduled_for", { ascending: true }); const nextCharges = (data ?? []) as Charge[]; setCharges(nextCharges); const ids = [...new Set(nextCharges.map(charge => charge.athlete_id).filter(Boolean))]; if (!ids.length) return setAthleteNames({}); const { data: athletes } = await supabase.from("athletes").select("id,first_name,last_name").in("id", ids); setAthleteNames(Object.fromEntries((athletes || []).map(athlete => [athlete.id, `${athlete.first_name} ${athlete.last_name}`]))); };
  useEffect(() => { void load(); }, []);
  const addCard = async () => { if (!supabase) return; setBusy(true); setMessage(""); const { data: { session } } = await supabase.auth.getSession(); if (!session) { setBusy(false); return setMessage("Vuelve a entrar antes de gestionar la tarjeta."); } const response = await fetch("/api/create-payment-method-setup", { method: "POST", headers: { authorization: `Bearer ${session.access_token}` } }); const body = await response.json().catch(() => ({})) as { url?: string; error?: string }; if (!response.ok || !body.url) { setBusy(false); return setMessage(body.error || "No se pudo abrir la pasarela de pago."); } window.location.assign(body.url); };
  const demoCharges = [{ id: "demo-1", title: "Matrícula de demostración", amount: 65, state: "Pagada · simulación" }, { id: "demo-2", title: "Cuota mensual · septiembre 2026", amount: 35, state: "Programada · simulación" }, { id: "demo-3", title: "Cuota mensual · octubre 2026", amount: 35, state: "Programada · simulación" }];
  if (isDemo) return <section className="billing-control"><div className="page-head"><div><h1>Cuotas y cobros</h1><p>Vista ficticia para revisar la experiencia del atleta.</p></div></div><p className="success-note panel"><b>MODO DEMOSTRACIÓN</b> · Estas cuotas no existen en Stripe y nunca se cobrarán.</p><article className="panel"><small>CALENDARIO FICTICIO</small><h2>3 cuotas de muestra</h2>{demoCharges.map(item => <div className="row athlete-row" key={item.id}><span><b>{item.title}</b><small>Atleta Demo · datos de prueba</small></span><span><b>{euro(item.amount * 100)}</b><small>{item.state}</small></span></div>)}</article><article className="panel"><h2>Pagos desactivados</h2><p>Este acceso no permite añadir tarjetas, abrir Stripe ni generar cargos.</p></article></section>;
  return <section className="billing-control"><div className="page-head"><div><h1>Cuotas y cobros</h1><p>Consulta el calendario de cuotas de tu temporada.</p></div></div><article className="panel"><small>MI CALENDARIO DE CUOTAS</small><h2>{charges.length ? `${charges.filter(charge => charge.status !== "paid").length} cuota(s) programada(s)` : "Sin cuotas programadas"}</h2>{charges.map(charge => { const amount = charge.approved_amount_cents ?? charge.calculated_amount_cents; const title = charge.charge_kind === "enrolment" ? "Matrícula" : charge.calculation_snapshot?.plan === "monthly" ? `Cuota mensual · ${new Date(`${charge.period_starts_on}T12:00:00`).toLocaleDateString("es-ES", { month: "long", year: "numeric" })}` : `Cuota trimestral · ${new Date(`${charge.period_starts_on}T12:00:00`).toLocaleDateString("es-ES", { month: "long" })}–${new Date(`${charge.period_ends_on}T12:00:00`).toLocaleDateString("es-ES", { month: "long", year: "numeric" })}`; return <button className="row athlete-row" key={charge.id} onClick={() => setOpen(open === charge.id ? "" : charge.id)}><span><b>{title}</b><small>Atleta: {athleteNames[charge.athlete_id] || (charge.athletes?.[0] ? `${charge.athletes[0].first_name} ${charge.athletes[0].last_name}` : "Atleta de la familia")}</small><small>Cargo previsto: {new Date(`${charge.scheduled_for}T12:00:00`).toLocaleDateString("es-ES")}</small>{open === charge.id && <small>Periodo: {charge.period_starts_on ? new Date(`${charge.period_starts_on}T12:00:00`).toLocaleDateString("es-ES") : "—"} al {charge.period_ends_on ? new Date(`${charge.period_ends_on}T12:00:00`).toLocaleDateString("es-ES") : "—"}</small>}</span><span><b>{euro(amount)}</b><small>{status(charge.status)}</small></span></button>; })}{!charges.length && <p>El club añadirá aquí las cuotas de tu temporada.</p>}</article><section className="two-columns"><article className="panel"><small>STRIPE · PAGO SEGURO</small><h2>Tarjeta para las cuotas</h2><p>Pasarela de pago 100% segura. El club no recibe ni guarda el número de tarjeta ni el CVV.</p><button disabled={busy} onClick={() => void addCard()}>{busy ? "Abriendo Stripe…" : "Añadir o cambiar tarjeta"}</button>{message && <p className="error-note">{message}</p>}</article><article className="panel"><h2>Pagos seguros</h2><p>El calendario queda aprobado al validar el alta. El club solo interviene si necesita modificar una excepción.</p></article></section></section>;
}
