import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import "./performance-advanced.css";

type Activity={started_at:string;activity_type:string|null;distance_m:number|null;moving_time_s:number|null;average_heartrate:number|null;relative_effort:number|null};
type Feedback={session_date:string;duration_minutes:number|null;rpe:number|null;pain_or_discomfort:boolean;fatigue_feeling:number|null};
type Plan={title:string;body:string;week_starts_on:string};
const running=new Set(["run","trailrun","virtualrun","wheelchair"]),days=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
const iso=(d:Date)=>d.toISOString().slice(0,10);const monday=(value=new Date())=>{const d=new Date(value);d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d};
const sessions=(plan:Plan|null)=>{if(!plan)return[];const normalized=plan.body.normalize("NFD").replace(/[\u0300-\u036f]/g,"");return days.map((day,index)=>{const key=day.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase(),start=normalized.search(new RegExp(`(^|\\n)${key}\\s*\\n`,"m"));if(start<0)return null;const rest=normalized.slice(start),next=days.map(item=>item.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase()).filter(item=>item!==key).map(item=>rest.slice(1).search(new RegExp(`\\n${item}\\s*\\n`))).filter(position=>position>=0).sort((a,b)=>a-b)[0],section=next===undefined?rest:rest.slice(0,next+1),duration=Number(section.match(/Duracion:\s*(\d+)/i)?.[1]||0),rpe=Number(section.match(/RPE:\s*(\d+)/i)?.[1]||0),date=new Date(`${plan.week_starts_on}T12:00:00`);date.setDate(date.getDate()+index);return{day,date:iso(date),duration,rpe}}).filter(Boolean) as {day:string;date:string;duration:number;rpe:number}[]};

export default function PerformanceAdvanced({athleteId}:{athleteId:string}){
 const[activities,setActivities]=useState<Activity[]>([]),[feedback,setFeedback]=useState<Feedback[]>([]),[plan,setPlan]=useState<Plan|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase)return;void(async()=>{setLoading(true);const athlete=await supabase.from("athletes").select("training_group_id").eq("id",athleteId).maybeSingle(),since=new Date();since.setDate(since.getDate()-180);const[a,f,p]=await Promise.all([supabase.from("external_sport_activities").select("started_at,activity_type,distance_m,moving_time_s,average_heartrate,relative_effort").eq("athlete_id",athleteId).gte("started_at",since.toISOString()).order("started_at"),supabase.from("athlete_training_feedback").select("session_date,duration_minutes,rpe,pain_or_discomfort,fatigue_feeling").eq("athlete_id",athleteId).gte("session_date",iso(since)).order("session_date"),athlete.data?.training_group_id?supabase.from("training_plans").select("title,body,week_starts_on").eq("training_group_id",athlete.data.training_group_id).not("published_at","is",null).lte("week_starts_on",iso(monday())).order("week_starts_on",{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null})]);setActivities(((a.data||[]) as Activity[]).filter(item=>running.has(String(item.activity_type||"").toLowerCase())));setFeedback((f.data||[]) as Feedback[]);setPlan((p.data||null) as Plan|null);setLoading(false)})()},[athleteId]);
 const planned=useMemo(()=>sessions(plan),[plan]),comparison=useMemo(()=>planned.map(session=>{const activity=activities.find(item=>item.started_at.slice(0,10)===session.date),manual=feedback.find(item=>item.session_date===session.date),duration=activity?Number(activity.moving_time_s||0)/60:Number(manual?.duration_minutes||0),load=activity?(Number(activity.relative_effort||0)||duration):duration*Number(manual?.rpe||0);return{...session,duration,load,done:Boolean(activity||manual),adherence:session.duration?Math.min(150,Math.round(duration/session.duration*100)):duration?100:0}}),[planned,activities,feedback]);
 const weeks=useMemo(()=>Array.from({length:12},(_,index)=>{const start=monday();start.setDate(start.getDate()-(11-index)*7);const end=new Date(start);end.setDate(end.getDate()+7);const items=activities.filter(item=>{const date=new Date(item.started_at);return date>=start&&date<end});return{label:start.toLocaleDateString("es-ES",{day:"2-digit",month:"short"}),distance:items.reduce((sum,item)=>sum+Number(item.distance_m||0)/1000,0),load:items.reduce((sum,item)=>sum+(Number(item.relative_effort||0)||Number(item.moving_time_s||0)/60),0)}}),[activities]);
 const recent=activities.filter(item=>new Date(item.started_at)>=new Date(Date.now()-28*86400000)),distance=recent.reduce((sum,item)=>sum+Number(item.distance_m||0)/1000,0),minutes=recent.reduce((sum,item)=>sum+Number(item.moving_time_s||0)/60,0),heartRates=recent.map(item=>Number(item.average_heartrate||0)).filter(Boolean),avgHr=heartRates.length?Math.round(heartRates.reduce((a,b)=>a+b,0)/heartRates.length):null,pace=distance?minutes/distance:null,completed=comparison.filter(item=>item.done).length,adherence=comparison.length?Math.round(comparison.reduce((sum,item)=>sum+Math.min(100,item.adherence),0)/comparison.length):null,recentPain=feedback.slice(-14).some(item=>item.pain_or_discomfort),recentFatigue=feedback.slice(-7).filter(item=>Number(item.fatigue_feeling||0)>=4).length,alerts=[recentPain?"Hay una molestia comunicada que conviene revisar.":"",recentFatigue>=2?"Se repite una percepción alta de fatiga.":"",weeks.at(-1)!.load>weeks.at(-2)!.load*1.5&&weeks.at(-2)!.load>0?"La carga semanal ha aumentado más de un 50 %.":""].filter(Boolean);
 if(loading)return <article className="performance-advanced-loading">Preparando comparativas y evolución…</article>;
 return <section className="performance-advanced"><article className="plan-reality"><header><div><small>PLANIFICADO FRENTE A REALIZADO</small><h3>{plan?.title||"Semana sin plan estructurado"}</h3></div>{adherence!==null&&<strong>{adherence}%<small>adherencia</small></strong>}</header>{comparison.length?<div>{comparison.map(item=><article key={item.date} className={item.done?item.adherence>=75&&item.adherence<=125?"matched":"different":"pending"}><span><b>{item.day}</b><small>{new Date(`${item.date}T12:00:00`).toLocaleDateString("es-ES",{day:"2-digit",month:"short"})}</small></span><span><small>PREVISTO</small><b>{item.duration||"—"} min · RPE {item.rpe||"—"}</b></span><span><small>REALIZADO</small><b>{item.done?`${Math.round(item.duration)} min · ${Math.round(item.load)} UA`:"Sin registrar"}</b></span><em>{item.done?`${item.adherence}%`:"Pendiente"}</em></article>)}</div>:<p>Cuando el entrenador publique una semana creada con el planificador aparecerá aquí día por día.</p>}</article><article className="season-evolution"><header><div><small>EVOLUCIÓN · 12 SEMANAS</small><h3>Carga y continuidad</h3></div><span>{weeks.at(-1)!.distance.toFixed(1)} km esta semana</span></header><div className="season-bars">{weeks.map((week,index)=>{const max=Math.max(...weeks.map(item=>item.load),1);return <span key={`${week.label}-${index}`}><i style={{height:`${Math.max(3,week.load/max*100)}%`}}/><small>{week.label}</small></span>})}</div><footer><span><b>{distance.toFixed(1)} km</b><small>últimos 28 días</small></span><span><b>{pace?`${Math.floor(pace)}:${String(Math.round((pace%1)*60)).padStart(2,"0")}`:"—"}</b><small>ritmo medio /km</small></span><span><b>{avgHr||"—"}</b><small>pulso medio</small></span><span><b>{completed}/{comparison.length||"—"}</b><small>sesiones completadas</small></span></footer></article><article className={`weekly-coach-report${alerts.length?" has-alerts":""}`}><header><i>✦</i><div><small>INFORME SEMANAL AUTOMÁTICO</small><h3>{alerts.length?"Aspectos que conviene revisar":"Semana sin alertas destacadas"}</h3></div></header>{alerts.length?<ul>{alerts.map(alert=><li key={alert}>{alert}</li>)}</ul>:<p>La carga, las sensaciones y el cumplimiento del plan no muestran señales destacadas. El informe se actualiza con cada actividad.</p>}<small>Resumen calculado sin consumo adicional de IA.</small></article></section>;
}
