import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import "./public-club-site.css";
import "./public-club-identity.css";
import "./public-hero-athletics.css";
type ClubIdentity={club_name:string;contact_email:string|null;contact_phone:string|null;season_label:string|null;registration_open:boolean|null;registration_message:string|null};
const mapsUrl="https://www.google.com/maps/search/?api=1&query=Estadio%20Ra%C3%BAl%20Gonz%C3%A1lez%20Blanco%20URJC%20Fuenlabrada";
const photo={hug:"/E6EF862A-8806-4F5B-A720-A7567B5E3C12.PNG",school:"/808601AC-3B03-4C64-AAF9-420E3B96B2F5.PNG",running:"/3A999C3C-FBAA-4641-B63D-DFB8A78805D2.png",training:"/athlete-hurdles-home.svg"};
function MapPin(){return <svg className="public-map-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a7 7 0 0 0-7 7c0 5.2 7 13 7 13s7-7.8 7-13a7 7 0 0 0-7-7Zm0 9.5A2.5 2.5 0 1 1 12 6a2.5 2.5 0 0 1 0 5.5Z"/></svg>}
export default function PublicClubSite({onLogin,onSignup}:{onLogin:()=>void;onSignup:()=>void}){const[identity,setIdentity]=useState<ClubIdentity|null>(null);useEffect(()=>{if(!supabase)return;void supabase.from("club_settings").select("club_name,contact_email,contact_phone,season_label,registration_open,registration_message").eq("id",true).maybeSingle().then(({data})=>{if(data)setIdentity(data as ClubIdentity)})},[]);const name=identity?.club_name||"Club Atletas de Fuenlabrada";const email=identity?.contact_email||"info@atletasdefuenlabrada.com";const scroll=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});const groups=()=>window.location.assign("/grupos-precios");return <main className="public-club-site">
<header className="public-nav"><button className="public-brand public-brand-wordmark" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><span>CLUB ATLETAS<small>DE FUENLABRADA</small></span></button><nav><button onClick={()=>scroll("club")}>El club</button><button onClick={groups}>Grupos y precios</button><button onClick={()=>scroll("running")}>Running</button><button onClick={()=>scroll("inscripcion")}>Inscripción</button><button onClick={()=>scroll("contacto")}>Contacto</button></nav><button className="public-login" onClick={onLogin}>Acceso privado</button></header>
<section className="public-hero"><div className="public-hero-copy"><small>ESCUELA DE ATLETISMO · COMPETICIÓN FEDERADA · RUNNING</small><h1>Tu entrenamiento.<br/>Tu club.<br/><em>Tu mejor versión.</em></h1><p>Desde los 4 años hasta Running y Máster. Un club para empezar, crecer, competir y seguir disfrutando del atletismo durante toda la vida deportiva.</p><div className="public-hero-actions"><button className="public-primary" onClick={onSignup}>Quiero inscribirme</button><button className="public-secondary" onClick={groups}>Ver grupos, horarios y precios</button></div><div className="public-season"><span>Temporada</span><b>{identity?.season_label||"2026 / 27"}</b></div></div><div className="public-hero-art" aria-hidden="true"><img className="public-hero-photo" src={photo.training}/><div className="track-ring ring-one"/><div className="track-ring ring-two"/><div className="track-ring ring-three"/><div className="hero-stat"><b>4+</b><span>años · toda una vida</span></div></div></section>
<section className="public-intro" id="club"><div><small>MUCHO MÁS QUE ENTRENAR</small><h2>Un club pensado para acompañarte toda la vida deportiva.</h2></div><p>Empezamos desde los 4 años y seguimos hasta los grupos de Running y Máster. Cada etapa tiene su propio entrenamiento, sus objetivos y su equipo, pero todos forman parte del mismo club.</p></section>
<section className="public-story-photo"><img src={photo.hug} alt="Atletas del club celebrando juntos tras una carrera"/><div><small>UN EQUIPO DENTRO Y FUERA DE LA PISTA</small><strong>Entrenamos juntos. Te acompañamos hasta la meta.</strong></div></section>
<section className="public-values"><article><span>01</span><h3>Escuela de atletismo</h3><p>Desde los 4 años. Aprendizaje progresivo de carrera, saltos y lanzamientos en un entorno adaptado a cada edad.</p></article><figure className="public-value-photo"><img src={photo.school} alt="Atleta Sub-14 del club con su entrenador y una medalla"/><figcaption><small>FORMACIÓN · PROGRESIÓN</small><b>Del primer entrenamiento a cada nuevo objetivo.</b></figcaption></figure><article><span>02</span><h3>Competición</h3><p>Preparación técnica, calendario, convocatorias, resultados y marcas reunidos en un mismo entorno para atletas y familias.</p></article><article><span>03</span><h3>Running y Máster</h3><p>Entrenamiento presencial para adultos, mejora de rendimiento y objetivos personales con continuidad durante toda la temporada.</p></article><article><span>04</span><h3>Una app para el club</h3><p>Plan semanal, avisos, cuotas, tienda, competiciones y evolución deportiva desde una sola cuenta.</p></article></section>
<section className="public-running" id="running"><div className="public-running-copy"><small>RUNNING · MÁSTER</small><h2>Cuatro días para entrenar mejor. Todo el año para seguir mejorando.</h2><p>Una de las propuestas de running más completas de Fuenlabrada y la zona sur: entrenamiento presencial, grupo, seguimiento y continuidad dentro del club.</p><div className="public-running-points"><span>4 entrenamientos presenciales por semana</span><span>70 € por trimestre</span><span>23,33 € al mes*</span></div></div><div className="public-running-media"><img src={photo.running} alt="Atleta del club durante una carrera de running"/></div><div className="public-running-price"><small>RUNNING / MÁSTER</small><b>23,33 €*</b><span>al mes</span><p>4 días de entrenamiento presencial por semana.</p><small className="public-price-note">* Equivalente mensual eligiendo la cuota trimestral de 70 €.</small><button className="public-primary" onClick={groups}>Ver horarios y matrícula</button></div></section>
<section className="public-digital"><div className="public-digital-card"><small>TODO EN TU CUENTA</small><h2>El entrenamiento continúa fuera de la pista.</h2><p>Cada atleta o familia dispone de su espacio personal para consultar lo que necesita durante la temporada.</p><div className="public-chip-row"><span>Plan semanal</span><span>Resultados</span><span>Marcas</span><span>Competiciones</span><span>Avisos</span><span>Cuotas</span></div></div><div className="public-phone-mock"><div><small>ESTA SEMANA</small><b>Plan de entrenamiento</b><span>Tu entrenador publica aquí el trabajo del grupo.</span></div><div><small>MI TEMPORADA</small><b>Marcas y resultados</b><span>Tu evolución deportiva siempre disponible.</span></div></div></section>
<section className="public-join" id="inscripcion"><div><small>INSCRIPCIONES</small><h2>Empieza tu temporada con nosotros.</h2><p>{identity?.registration_message||"Crea tu cuenta, completa los datos del atleta y el club revisará la solicitud antes de activar el alta."}</p></div><div className="public-join-steps"><span><b>1</b>Crea tu cuenta</span><span><b>2</b>Completa la inscripción</span><span><b>3</b>El club revisa el alta</span></div><button className="public-primary" onClick={onSignup}>{identity?.registration_open===false?"Solicitar información":"Iniciar inscripción"}</button></section>
<section className="public-contact" id="contacto"><div><small>DÓNDE ENTRENAMOS</small><h2>Estadio Raúl González Blanco</h2><p>Universidad Rey Juan Carlos · Campus de Fuenlabrada</p><a className="public-map-link" href={mapsUrl} target="_blank" rel="noreferrer"><MapPin/><span><b>Cómo llegar</b><small>Abrir en Google Maps</small></span></a></div><div className="public-contact-data"><a href={`mailto:${email}`}>{email}</a>{identity?.contact_phone&&<a href={`tel:${identity.contact_phone.replace(/\s/g,"")}`}>{identity.contact_phone}</a>}<button onClick={onLogin}>Ya soy del club → Acceder</button></div></section>
<section className="public-collaborators"><small>COLABORADORES</small><div><article><img src="/IMG_4849.PNG" alt="Universidad Rey Juan Carlos"/><span>Universidad Rey Juan Carlos</span></article><article><img src="/IMG_4848.JPG" alt="Ayuntamiento de Fuenlabrada · Concejalía de Deportes"/><span>Ayuntamiento de Fuenlabrada · Concejalía de Deportes</span></article></div></section><footer className="public-footer"><div className="public-brand public-brand-wordmark public-brand-footer"><span>CLUB ATLETAS<small>DE FUENLABRADA</small></span></div><p>{name} · Plataforma oficial del club.</p><button onClick={onLogin}>Acceso familias, atletas y equipo</button></footer></main>}
