import { useState } from "react";
import { createRoot } from "react-dom/client";
import "./demo.css";

// Standalone entry: never import the real app, authentication, payment or API modules.
const people = ["Álex Demo", "Cris Demo", "Dani Demo", "Mar Demo", "Sam Demo", "Vega Demo"];
const groups = ["Running A", "Running B", "Escuela"];
const initialPlan = ["Rodaje suave · 35 minutos", "Técnica + 6 × 400 m", "Descanso", "Rodaje progresivo · 40 minutos", "Fuerza y movilidad", "Rodaje en grupo · 50 minutos", "Descanso"];
const days = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"];
type Role = "Administrador" | "Entrenador" | "Familia / atleta";
function Demo() {
  const [role, setRole] = useState<Role>("Administrador");
  const [tab, setTab] = useState("Resumen");
  const [group, setGroup] = useState(groups[0]);
  const [plans, setPlans] = useState<Record<string, string[]>>({});
  const [attendance, setAttendance] = useState<Record<string, boolean>>({});
  const [date, setDate] = useState("2026-09-09");
  const [editing, setEditing] = useState(false);
  const [challenge, setChallenge] = useState(false);
  const [notice, setNotice] = useState("");
  const [message, setMessage] = useState("");
  const [sent, setSent] = useState<string[]>([]);
  const plan = plans[group] || initialPlan;
  const staff = role !== "Familia / atleta";
  const tabs = ["Resumen", "Planes", ...(staff ? ["Asistencia"] : []), ...(role === "Administrador" ? ["Cuotas"] : []), "Challenge", "Avisos"];
  const reset = () => { setPlans({}); setAttendance({}); setSent([]); setChallenge(false); setMessage(""); setNotice("Demostración reiniciada. No se ha modificado ninguna cuenta real."); };
  return <div className="demo-shell">
    <div className="demo-banner">MODO DEMOSTRACIÓN · Datos ficticios · Sin cobros, correos ni conexiones externas</div>
    <header><div><small>SPORTMED / CLUB EXPERIENCE</small><h1>Tu club, en movimiento</h1><p>La experiencia digital que conecta, organiza y hace crecer tu club.</p></div><button onClick={reset}>Reiniciar demo</button></header>
    <section className="demo-controls"><label>Explorar como<select value={role} onChange={e => { const nextRole = e.target.value as Role; setRole(nextRole); setTab("Resumen"); setEditing(false); setNotice(`Vista cambiada a ${nextRole}.`); }}>{["Administrador", "Entrenador", "Familia / atleta"].map(r => <option key={r}>{r}</option>)}</select></label><label>Grupo<select value={group} onChange={e => { setGroup(e.target.value); setEditing(false); }}>{groups.map(g => <option key={g}>{g}</option>)}</select></label><span className="demo-role">Panel de {role.toLowerCase()}</span></section>
    <nav aria-label="Secciones de demostración">{tabs.map(t => <button key={t} aria-current={tab === t ? "page" : undefined} onClick={() => { setTab(t); setEditing(false); }}>{t}</button>)}</nav>
    {notice && <p role="status" className="demo-status">{notice}</p>}
    <main>
      {tab === "Resumen" && role === "Administrador" && <><div className="demo-title"><small>PANEL DE ADMINISTRACIÓN</small><h2>El club completo, bajo control.</h2><p>Una visión global de deportistas, grupos, cobros y actividad para tomar decisiones con claridad.</p></div><div className="demo-metrics">{[["18", "Atletas de ejemplo"], ["3", "Grupos activos"], ["12", "Matrículas con importe"], ["960 €", "Matrículas simuladas"]].map(([v,l]) => <article key={l}><strong>{v}</strong><span>{l}</span></article>)}</div><div className="demo-grid"><article><small>GESTIÓN DEPORTIVA</small><h3>Planes de todos los grupos</h3><p>Consulta y coordina la semana de {group}.</p><button onClick={() => setTab("Planes")}>Gestionar planes</button></article><article><small>CONTROL FINANCIERO</small><h3>Cuotas y matrículas</h3><p>Seguimiento simulado de cobros, incidencias y previsiones.</p><button onClick={() => setTab("Cuotas")}>Abrir cuotas</button></article></div></>}
      {tab === "Resumen" && role === "Entrenador" && <><div className="demo-title"><small>PANEL DEL ENTRENADOR</small><h2>Tu grupo, preparado para entrenar.</h2><p>Aquí solo aparece la información deportiva necesaria para organizar {group}, publicar el plan y pasar lista.</p></div><div className="demo-metrics">{[["6", "Atletas del grupo"], ["4", "Sesiones esta semana"], ["1", "Plan publicado"], ["83 %", "Asistencia media"]].map(([v,l]) => <article key={l}><strong>{v}</strong><span>{l}</span></article>)}</div><div className="demo-grid"><article><small>PRÓXIMA SESIÓN</small><h3>{group}</h3><p>{plan[0]}</p><button onClick={() => setTab("Planes")}>Abrir plan semanal</button></article><article><small>ASISTENCIA</small><h3>Lista preparada</h3><p>Consulta días anteriores o registra a varios atletas sin perder selecciones.</p><button onClick={() => setTab("Asistencia")}>Pasar lista</button></article></div></>}
      {tab === "Resumen" && role === "Familia / atleta" && <><div className="demo-title"><small>ESPACIO DEL ATLETA Y LA FAMILIA</small><h2>Tu semana, siempre clara.</h2><p>Entrenamientos, avisos y retos personales en una vista sencilla, sin información administrativa del club.</p></div><div className="demo-metrics">{[["4", "Sesiones esta semana"], ["2", "Entrenamientos completados"], ["38 km", "Kilómetros del mes"], ["5 días", "Racha personal"]].map(([v,l]) => <article key={l}><strong>{v}</strong><span>{l}</span></article>)}</div><div className="demo-grid"><article><small>PRÓXIMO ENTRENAMIENTO</small><h3>{group}</h3><p>{plan[0]}</p><button onClick={() => setTab("Planes")}>Ver mi semana</button></article><article><small>MI PROGRESO</small><h3>Reto colectivo · 500 km</h3><p>Tu aportación de ejemplo: 38 km. El club lleva 312 km.</p><progress max="500" value="312"/><button onClick={() => setTab("Challenge")}>Ver mis retos</button></article></div></>}
      {tab === "Planes" && <><div className="demo-title"><h2>Tu semana en movimiento</h2><p>{group} · Plan publicado de ejemplo, no una prescripción personal.</p>{staff && <button onClick={() => { if (editing) setNotice("Plan publicado solo en esta demostración."); setEditing(!editing); }}>{editing ? "Publicar en la demo" : "Editar plan de ejemplo"}</button>}</div><div className="demo-week">{days.map((d,i) => <article key={d}><small>{d}</small>{editing ? <textarea aria-label={`Plan del ${d}`} value={plan[i]} onChange={e => setPlans({...plans, [group]: plan.map((p,j) => j === i ? e.target.value : p)})}/> : <h3>{plan[i]}</h3>}</article>)}</div></>}
      {tab === "Asistencia" && staff && <><h2>Pasar lista · {group}</h2><label>Fecha<input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><p>Marca varios atletas o cambia la fecha para consultar otra lista de ejemplo.</p><div className="demo-grid">{people.map(name => { const key = `${group}/${date}/${name}`; return <label className="demo-person" key={name}><input type="checkbox" checked={!!attendance[key]} onChange={e => setAttendance(a => ({...a,[key]: e.target.checked}))}/>{name}</label>; })}</div><p>Guardado únicamente en memoria, sin datos reales.</p></>}
      {tab === "Cuotas" && role === "Administrador" && <><h2>Matrículas cobradas · Simulación</h2><p>12 matrículas con importe · 960 €. Las 6 renovaciones de 0 € no se cuentan como matrículas cobradas.</p><div className="demo-table"><table><thead><tr><th>Atleta ficticio</th><th>Concepto</th><th>Importe</th><th>Estado</th></tr></thead><tbody>{groups.flatMap((g,gi) => people.map((p,i) => <tr key={`${g}/${p}`}><td>{p} · {g}</td><td>{i < 4 ? "Matrícula" : "Renovación"}</td><td>{i < 4 ? "80 €" : "0 €"}</td><td>{i < 4 ? "Cobro simulado" : "Sin cargo"}{gi === -1 ? "" : ""}</td></tr>))}</tbody></table></div></>}
      {tab === "Challenge" && <><h2>Challenge / Superarse juntos</h2><p>Clasificación ficticia. Los retos no recomiendan aumentar la carga ni saltarse descansos.</p><div className="demo-podium">{[1,0,2].map((n) => <article key={n}><small>POSICIÓN {n+1}</small><h3>{people[n]}</h3><strong>{[42,38,31][n]} km</strong></article>)}</div><div className="demo-grid"><article><h3>Reto colectivo · 500 km</h3><progress value="312" max="500"/><p>{challenge ? "Participas en este reto de demostración." : "Sumamos kilómetros entre todos, cada uno a su ritmo."}</p><button onClick={() => setChallenge(!challenge)}>{challenge ? "Salir del reto demo" : "Unirme al reto demo"}</button></article><article><h3>Duelo de constancia</h3><p>Invita a Cris Demo a cumplir las sesiones planificadas esta semana.</p><button onClick={() => setNotice("Invitación simulada a Cris Demo. No se ha enviado ninguna notificación.")}>Simular invitación</button></article></div></>}
      {tab === "Avisos" && <><h2>El club, al día</h2><article><h3>Bienvenidos a la nueva temporada</h3><p>Este mensaje forma parte de la demostración comercial de Sportmed.</p></article>{sent.map((s,i) => <article key={i}><small>PUBLICACIÓN SIMULADA</small><p>{s}</p></article>)}{staff && <form onSubmit={e => { e.preventDefault(); if (!message.trim()) return; setSent(s => [...s,message.trim()]); setMessage(""); setNotice("Aviso añadido a esta demo. No se han enviado correos ni notificaciones."); }}><label>Nuevo aviso de ejemplo<textarea required maxLength={1000} value={message} onChange={e => setMessage(e.target.value)}/></label><button>Publicar solo en la demo</button></form>}</>}
    </main><footer>Sportmed · Demostración comercial independiente. No introduzcas datos personales reales. Recargar borra los cambios.</footer>
  </div>;
}
createRoot(document.getElementById("root")!).render(<Demo/>);
